import { useEffect,useMemo,useState } from 'react'
import { Award,BookOpen,CheckCircle2,Flame,Lock,Star,Trophy,Zap } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../../services/api'

const badgeDefs=[
 {id:'first',name:'First Step',desc:'Start your first course.',icon:Zap,check:c=>c.length>0},
 {id:'half',name:'Halfway There',desc:'Reach 50% progress in a course.',icon:Star,check:c=>c.some(x=>Number(x.progress_percent||0)>=50)},
 {id:'finisher',name:'Course Finisher',desc:'Complete a course.',icon:CheckCircle2,check:c=>c.some(x=>x.completed||x.enrollment_status==='completed')},
 {id:'explorer',name:'Learning Explorer',desc:'Be active across three courses.',icon:BookOpen,check:c=>c.filter(x=>Number(x.progress_percent||0)>0).length>=3},
 {id:'mastery',name:'Learning Mastery',desc:'Complete three courses.',icon:Trophy,check:c=>c.filter(x=>x.completed||x.enrollment_status==='completed').length>=3},
]
export default function Achievements(){const [data,setData]=useState([]),[error,setError]=useState('');useEffect(()=>{api.learnerCourses().then(x=>setData(Array.isArray(x)?x:(x.courses||[]))).catch(e=>setError(e.message))},[]);const earned=useMemo(()=>badgeDefs.filter(b=>b.check(data)),[data]);if(error)return <div className="six-surface border p-6 text-red-600">{error}</div>;return <div className="space-y-7"><div><div className="text-sm six-primary-text font-semibold">Training journey</div><h1 className="text-3xl font-bold mt-1">Achievements</h1><p className="six-muted mt-1">Milestones are calculated from your current learning progress.</p></div><div className="six-surface border p-6 six-animate-rise"><div className="flex items-center gap-4"><div className="w-14 h-14 rounded-2xl six-primary-soft flex items-center justify-center"><Trophy className="six-primary-text"/></div><div><div className="text-2xl font-bold">{earned.length} / {badgeDefs.length}</div><div className="six-muted text-sm">milestones unlocked</div></div></div><div className="mt-5 h-3 rounded-full overflow-hidden" style={{background:'var(--hover)'}}><div className="h-full six-primary-bg six-progress-fill" style={{width:`${earned.length/badgeDefs.length*100}%`}}/></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{badgeDefs.map((b,i)=>{const isEarned=earned.some(x=>x.id===b.id),Icon=b.icon;return <div key={b.id} style={{animationDelay:`${i*60}ms`}} className={`six-surface border p-5 six-task-card six-animate-rise ${isEarned?'six-complete':''}`}><div className="flex items-start justify-between"><div className="w-11 h-11 rounded-xl flex items-center justify-center" style={{background:isEarned?'var(--primary-soft)':'var(--hover)'}}><Icon className={isEarned?'six-primary-text':'six-muted'} size={22}/></div>{isEarned?<span className="text-xs six-primary-text font-semibold">Unlocked</span>:<Lock size={17} className="six-muted"/>}</div><h2 className="font-bold mt-5">{b.name}</h2><p className="six-muted text-sm mt-1">{b.desc}</p></div>})}</div><div className="six-surface border p-6"><div className="flex items-center gap-3"><Flame className="six-primary-text"/><div><h2 className="font-bold">Keep the momentum</h2><p className="six-muted text-sm">Continue an active course to unlock more milestones.</p></div></div><Link to="/my-courses" className="six-button inline-flex mt-4 px-4 py-2 rounded-xl text-sm">Continue learning</Link></div></div>}
