import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, ChevronDown, ClipboardCheck, Clock3, FileText, Flag, Lightbulb, ListChecks, PlayCircle, RotateCcw, Send, Sparkles, TimerReset, Wrench, Bookmark, BookmarkCheck, Maximize2, PlayCircle, StickyNote, ExternalLink } from 'lucide-react'
import { api } from '../../services/api'
import Tooltip from '../../components/common/Tooltip'

const iconFor=t=>t==='lesson'?BookOpen:t==='activity'?ClipboardCheck:t==='assessment'?TimerReset:FileText
const keyFor=(e,i)=>`sixele.player.${e}.${i.item_type}.${i.id}`
const fmt=s=>{const m=Math.floor(Math.max(0,s)/60), sec=Math.max(0,s)%60; return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}

export default function LearningWorkspace(){
 const {enrollmentId}=useParams();
 const [data,setData]=useState(null),[error,setError]=useState(''),[item,setItem]=useState(null),[detail,setDetail]=useState(null),[text,setText]=useState(''),[answer,setAnswer]=useState({}),[checks,setChecks]=useState([]),[busy,setBusy]=useState(false),[celebrate,setCelebrate]=useState(false),[seconds,setSeconds]=useState(null),[tipOpen,setTipOpen]=useState(true),[bookmarked,setBookmarked]=useState(false),[notes,setNotes]=useState(''),[videoProgress,setVideoProgress]=useState(0)
 const playerRef=useRef(null); const videoRef=useRef(null); const load=()=>api.learnerExperience(enrollmentId).then(d=>{setData(d);setItem(x=>x||d.current_item)}).catch(e=>setError(e.message))
 useEffect(()=>{load()},[enrollmentId])
 useEffect(()=>{if(!item)return; setDetail(null); const raw=localStorage.getItem(keyFor(enrollmentId,item)); if(raw){try{const s=JSON.parse(raw);setText(s.text||'');setAnswer(s.answer||{});setChecks(s.checks||[]);setNotes(s.notes||'');setBookmarked(!!s.bookmarked);setVideoProgress(Number(s.videoProgress||0))}catch{}} const fn=item.item_type==='lesson'?api.learnerLesson(enrollmentId,item.id):item.item_type==='activity'?api.learnerActivity(enrollmentId,item.id):item.item_type==='assessment'?api.learnerQuiz(enrollmentId,item.id):api.learnerAssignment(enrollmentId,item.id); fn.then(d=>{setDetail(d);setSeconds(d.duration_minutes?d.duration_minutes*60:null);setChecks(d.checklist||[]) }).catch(e=>setError(e.message))},[item,enrollmentId])
 useEffect(()=>{if(!item)return;localStorage.setItem(keyFor(enrollmentId,item),JSON.stringify({text,answer,checks,notes,bookmarked,videoProgress}))},[text,answer,checks,enrollmentId,item])
 useEffect(()=>{if(seconds===null||seconds<=0)return;const id=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(id)},[seconds])
 useEffect(()=>{if(seconds===0&&detail&&item?.item_type==='activity') setTipOpen(true)},[seconds,detail,item])
 const toggleFullscreen=()=>{if(playerRef.current?.requestFullscreen) playerRef.current.requestFullscreen()}; const resourceList=detail?.resources||detail?.resource_links||[]; const videoUrl=detail?.video_url||detail?.videoUrl||detail?.media_url||detail?.mediaUrl; const feedback=detail?.feedback||detail?.instructor_feedback||detail?.latest_feedback; const toggleBookmark=()=>setBookmarked(v=>!v);
 if(error)return <div className="six-surface border p-6 text-red-600">{error}</div>
 if(!data)return <div className="six-muted">Loading course…</div>
 const Icon=iconFor(item.item_type)
 const move=dir=>{const i=data.items.findIndex(x=>x.id===item.id&&x.item_type===item.item_type);const n=data.items[i+dir];if(n)setItem(n)}
 const celebrateNow=()=>{setCelebrate(true);setTimeout(()=>setCelebrate(false),1800)}
 const submit=async()=>{if(!detail)return;setBusy(true);try{if(item.item_type==='activity')await api.submitActivity(enrollmentId,item.id,{text_response:text,files:[],checklist:checks,evidence_notes:text});else if(item.item_type==='assignment')await api.submitAssignment(enrollmentId,item.id,{text_response:text,files:[],deliverable_notes:text});else if(item.item_type==='assessment'){const answers=Object.entries(answer).map(([question_id,a])=>({question_id,answer:Array.isArray(a)?a:[a]}));await api.submitQuiz(enrollmentId,item.id,{answers})} localStorage.removeItem(keyFor(enrollmentId,item));setText('');setAnswer({});celebrateNow();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const checklist=useMemo(()=>detail?.checklist||[],[detail])
 const doneChecks=checks.filter(Boolean).length
 return <div className="space-y-5 relative">
  {celebrate&&<div className="six-celebration" aria-live="polite"><div className="six-celebration-card"><Sparkles className="six-primary-text"/><div><b>Great work!</b><p className="six-muted text-sm">Your task was submitted successfully.</p></div></div><div className="six-confetti">{Array.from({length:18}).map((_,i)=><i key={i} style={{'--i':i}}/>)}</div></div>}
  <div className="flex items-center justify-between gap-4"><Link to="/my-courses" className="six-muted text-sm inline-flex items-center gap-2"><ArrowLeft size={16}/> My Courses</Link><Tooltip text="See course completion requirements"><Link to={`/learn/${enrollmentId}/progress`} className="six-primary-text text-sm font-medium">View progress</Link></Tooltip></div>
  <div className="grid xl:grid-cols-[300px_1fr] gap-5">
   <aside className="six-surface border p-4 six-animate-rise"><h1 className="font-bold text-lg px-2">{data.course_title}</h1><div className="mt-3 h-2 rounded-full overflow-hidden" style={{background:'var(--hover)'}}><div className="six-primary-bg h-2 rounded-full six-progress-fill" style={{width:`${data.progress_percent}%`}}/></div><div className="text-xs six-muted mt-2">{data.completed_items}/{data.total_items} items completed</div><div className="mt-5 space-y-1 max-h-[65vh] overflow-auto">{data.items.map((x,index)=>{const I=iconFor(x.item_type);return <button key={`${x.item_type}-${x.id}`} onClick={()=>setItem(x)} style={{animationDelay:`${Math.min(350,index*25)}ms`}} className={`w-full text-left flex gap-3 items-center p-3 rounded-xl text-sm six-task-card six-animate-pop ${item.id===x.id?'six-primary-soft six-primary-text':'six-hover'}`}><I size={17}/><span className="flex-1">{x.title}</span>{x.completed&&<CheckCircle2 size={16}/>}</button>})}</div></aside>
   <main ref={playerRef} className="six-surface border p-4 sm:p-6 md:p-8 six-animate-rise">
    {detail&&<>
     <div className="flex flex-wrap items-center gap-3"><Icon className="six-primary-text"/><span className="text-xs uppercase tracking-wide six-muted">{item.item_type}</span>{detail.is_required&&<span className="text-xs px-2 py-1 rounded-lg six-primary-soft six-primary-text">Required</span>}{seconds!==null&&<span className={`ml-auto inline-flex items-center gap-2 text-sm font-semibold ${seconds<60?'text-red-600':'six-primary-text'}`}><Clock3 size={16}/>{fmt(seconds)}</span>}</div>
     <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl md:text-3xl font-bold mt-4">{detail.title}</h2><p className="six-muted mt-2">{detail.description}</p></div><div className="flex gap-2"><Tooltip text={bookmarked?'Remove bookmark':'Bookmark this item'}><button onClick={toggleBookmark} className="six-icon-button border" aria-label="Bookmark">{bookmarked?<BookmarkCheck size={17}/>:<Bookmark size={17}/>}</button></Tooltip><Tooltip text="Open the learning workspace in full screen"><button onClick={toggleFullscreen} className="six-icon-button border" aria-label="Fullscreen"><Maximize2 size={17}/></button></Tooltip><div className="six-tool-chip"><Wrench size={15}/> Learning tool</div></div></div>
     {item.item_type==='lesson'&&<LessonMedia detail={detail} videoRef={videoRef} videoProgress={videoProgress} setVideoProgress={setVideoProgress}/>}
     {item.item_type==='lesson'&&<Lesson detail={detail} complete={async()=>{setBusy(true);try{await api.completeLesson(enrollmentId,item.id);celebrateNow();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}} busy={busy}/>} 
     {item.item_type==='activity'&&<section className="mt-7 space-y-5"><InfoBlock title="Instructions" icon={BookOpen}>{detail.instructions}</InfoBlock><InfoBlock title="Task" icon={ClipboardCheck}>{detail.task_description}</InfoBlock><div className="six-task-tip"><div className="flex items-start gap-3"><Lightbulb size={19} className="six-primary-text mt-0.5"/><div className="flex-1"><div className="font-semibold">Task tip</div><p className="text-sm six-muted mt-1">Work through the checklist first, then describe what you did and what evidence an instructor should look for.</p></div><button onClick={()=>setTipOpen(v=>!v)} className="six-icon-button"><ChevronDown size={17} className={tipOpen?'rotate-180':''}/></button></div>{tipOpen&&<div className="mt-3 text-sm six-muted border-t pt-3">Use clear, observable evidence: what you changed, how you verified it, and any result or reflection that matters.</div>}</div>{checklist.length>0&&<div className="border rounded-2xl p-5"><div className="flex items-center justify-between"><h3 className="font-semibold inline-flex items-center gap-2"><ListChecks size={18}/> Task checklist</h3><span className="text-xs six-muted">{doneChecks}/{checklist.length}</span></div><div className="mt-4 space-y-2">{checklist.map((c,i)=><label key={i} className="flex gap-3 items-start border rounded-xl p-3 six-hover cursor-pointer"><input type="checkbox" checked={!!checks[i]} onChange={e=>setChecks(a=>{const n=[...a];n[i]=e.target.checked;return n})}/><span className={checks[i]?'line-through six-muted':''}>{typeof c==='string'?c:c.label||c.title}</span></label>)}</div></div>}<textarea className="six-input rounded-xl w-full p-4 min-h-40" placeholder="Enter your response or evidence notes…" value={text} onChange={e=>setText(e.target.value)}/><Tooltip text="Send your completed task for instructor review"><button disabled={busy||detail.attempts_used>=detail.attempts_allowed||seconds===0} onClick={submit} className="six-button px-5 py-3 rounded-xl inline-flex gap-2 six-animate-pop"><Send size={17}/>Submit activity</button></Tooltip></section>}
     {item.item_type==='assignment'&&<section className="mt-7 space-y-5"><InfoBlock title="Project brief" icon={FileText}>{detail.brief||detail.instructions||detail.description}</InfoBlock><div className="border rounded-2xl p-5"><h3 className="font-semibold inline-flex items-center gap-2"><Flag size={18}/> Deliverables</h3><ul className="list-disc ml-5 six-muted mt-3 space-y-1">{(detail.deliverables||[]).map((d,i)=><li key={i}>{typeof d==='string'?d:d.label||d.title}</li>)}</ul></div><textarea className="six-input rounded-xl w-full p-4 min-h-40" placeholder="Write your submission or deliverable notes…" value={text} onChange={e=>setText(e.target.value)}/><button disabled={busy||detail.attempts_used>=detail.attempts_allowed} onClick={submit} className="six-button px-5 py-3 rounded-xl inline-flex gap-2"><Send size={17}/>Submit assignment</button></section>}
     {item.item_type==='assessment'&&<section className="mt-7"><Link to={`/learn/${enrollmentId}/assessment/quiz/${item.id}`} className="six-button inline-flex px-4 py-2 rounded-xl text-sm mb-5">Open assessment workspace</Link><p className="six-muted">{detail.instructions}</p></section>}
    </>}
    {!detail&&<div className="six-muted">Loading learning item…</div>}
    {detail&&<div className="mt-8 grid lg:grid-cols-2 gap-4">
      <section className="border rounded-2xl p-5"><h3 className="font-semibold inline-flex items-center gap-2"><StickyNote size={18}/> My notes</h3><textarea className="six-input rounded-xl w-full p-3 mt-3 min-h-28" placeholder="Capture a useful note for this lesson…" value={notes} onChange={e=>setNotes(e.target.value)}/><p className="six-muted text-xs mt-2">Saved automatically on this device.</p></section>
      {feedback&&<section className="six-task-tip"><h3 className="font-semibold">Instructor feedback</h3><p className="six-muted text-sm mt-2">{typeof feedback==='string'?feedback:feedback.comment||feedback.message||feedback.text}</p></section>}
    </div>}
    {detail&&resourceList.length>0&&<section className="mt-4 border rounded-2xl p-5"><h3 className="font-semibold inline-flex items-center gap-2"><FileText size={18}/> Learning resources</h3><div className="mt-3 grid sm:grid-cols-2 gap-2">{resourceList.map((r,i)=>{const url=r.url||r.file_url||r.download_url;return <a key={i} href={url||'#'} target={url?'_blank':undefined} rel="noreferrer" className="flex items-center gap-3 border rounded-xl p-3 six-hover"><FileText size={17}/><span className="flex-1 text-sm">{r.name||r.title||r.filename||`Resource ${i+1}`}</span>{url&&<ExternalLink size={15}/>}</a>})}</div></section>}
    <div className="flex justify-between mt-10 pt-5 border-t"><Tooltip text="Previous item"><button className="six-muted p-2 rounded-xl six-hover" onClick={()=>move(-1)} aria-label="Previous item"><ArrowLeft/></button></Tooltip><Tooltip text="Next item"><button className="six-button px-4 py-2 rounded-xl" onClick={()=>move(1)} aria-label="Next item"><ArrowRight/></button></Tooltip></div>
   </main>
  </div>
 </div>
}
function LessonMedia({detail,videoRef,videoProgress,setVideoProgress}){ const url=detail?.video_url||detail?.videoUrl||detail?.media_url||detail?.mediaUrl; if(!url)return null; return <div className="mt-6 rounded-2xl overflow-hidden border bg-black six-animate-rise"><video ref={videoRef} className="w-full max-h-[62vh]" controls playsInline onTimeUpdate={e=>{const v=e.currentTarget;setVideoProgress(v.duration?Math.round(v.currentTime/v.duration*100):0)}} onLoadedMetadata={e=>{if(videoProgress>0&&e.currentTarget.duration)e.currentTarget.currentTime=e.currentTarget.duration*videoProgress/100}} src={url}/><div className="bg-black/90 text-white px-4 py-2 flex items-center gap-2 text-xs"><PlayCircle size={15}/><span>{videoProgress}% watched</span><div className="h-1.5 rounded-full bg-white/20 flex-1 overflow-hidden"><div className="h-full six-primary-bg" style={{width:`${videoProgress}%`}}/></div></div></div> }

function InfoBlock({title,icon:Icon,children}){return <div><h3 className="font-semibold inline-flex items-center gap-2"><Icon size={18}/>{title}</h3><p className="whitespace-pre-wrap six-muted mt-2 leading-7">{children}</p></div>}
function Lesson({detail,complete,busy}){return <section className="mt-7"><div className="six-lesson-tools"><span><PlayCircle size={17}/> Focus mode</span><span><RotateCcw size={16}/> Review before completing</span></div><div className="mt-6 whitespace-pre-wrap six-body-text leading-8">{detail.content}</div><button disabled={detail.completed||busy} onClick={complete} className="six-button mt-7 px-5 py-3 rounded-xl inline-flex gap-2 disabled:opacity-50">{detail.completed?<><Check size={17}/>Lesson completed</>:<><CheckCircle2 size={17}/>Mark lesson complete</>}</button></section>}
