import {useEffect,useMemo,useState} from 'react'
import {UsersRound,UserPlus,Search,RefreshCw,X,CheckCircle2,Clock3,Ban,AlertCircle} from 'lucide-react'
import {api} from '../../services/api'
import {usePermissions} from '../../contexts/PermissionContext'
const Input=p=><input {...p} className={`six-input w-full rounded-xl px-3 py-2.5 outline-none ${p.className||''}`}/>
function Modal({title,onClose,children}){return <div className="fixed inset-0 z-50 bg-black/40 p-4 flex items-center justify-center"><div className="six-surface w-full max-w-2xl max-h-[90vh] overflow-hidden"><div className="p-5 border-b six-border flex justify-between"><h2 className="text-lg font-semibold">{title}</h2><button onClick={onClose} className="p-2 six-hover rounded-lg"><X size={18}/></button></div><div className="p-5 overflow-y-auto">{children}</div></div></div>}
const statusMeta={active:['Active','bg-green-100 text-green-700'],completed:['Completed','bg-blue-100 text-blue-700'],cancelled:['Cancelled','bg-gray-100 text-gray-600']}
export default function EnrollmentManagement(){const{can}=usePermissions();const[rows,setRows]=useState([]),[courses,setCourses]=useState([]),[learners,setLearners]=useState([]),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[courseId,setCourseId]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[selected,setSelected]=useState([]),[selectedCourse,setSelectedCourse]=useState(''),[saving,setSaving]=useState(false)
 const load=async()=>{setLoading(true);try{const [e,c,u]=await Promise.all([api.adminEnrollments({search,status,course_id:courseId}),api.courses({status:'published'}),api.users({active:true})]);setRows(e);setCourses(c);setLearners(u.filter(x=>!x.is_super_admin));setError('')}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[search,status,courseId])
 const stats=useMemo(()=>({total:rows.length,active:rows.filter(x=>x.status==='active').length,completed:rows.filter(x=>x.status==='completed').length,cancelled:rows.filter(x=>x.status==='cancelled').length}),[rows])
 const enroll=async e=>{e.preventDefault();if(!selectedCourse||!selected.length)return;setSaving(true);try{await api.bulkEnroll(selectedCourse,selected);setOpen(false);setSelected([]);setSelectedCourse('');await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 const cancel=async id=>{if(!confirm('Cancel this enrollment?'))return;try{await api.cancelEnrollment(id);await load()}catch(e){setError(e.message)}}
 return <div className="p-4 sm:p-6 space-y-5"><div className="flex flex-col sm:flex-row justify-between gap-4"><div><div className="flex items-center gap-2"><UsersRound className="six-primary-text"/><h1 className="text-2xl font-bold">Enrollment Management</h1></div><p className="six-muted mt-1">Enroll learners, monitor progress and manage course access.</p></div>{can('enrollments.manage')&&<button onClick={()=>setOpen(true)} className="six-button rounded-xl px-4 py-2.5 flex gap-2 items-center"><UserPlus size={18}/>Enroll learners</button>}</div>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Total',stats.total],['Active',stats.active],['Completed',stats.completed],['Cancelled',stats.cancelled]].map(([l,v])=><div className="six-surface border p-4" key={l}><div className="text-xs six-muted">{l}</div><div className="text-2xl font-bold mt-1">{v}</div></div>)}</div>
 <div className="six-surface border p-4 grid md:grid-cols-[1fr_200px_220px_auto] gap-3"><div className="relative"><Search className="absolute left-3 top-3 six-muted" size={18}/><Input className="pl-10" placeholder="Search learner or course" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="six-input rounded-xl px-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><select className="six-input rounded-xl px-3" value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">All courses</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><button onClick={load} className="six-hover rounded-xl px-3"><RefreshCw size={18}/></button></div>
 {error&&<div className="rounded-xl bg-red-50 text-red-700 p-3 flex gap-2"><AlertCircle size={18}/>{error}</div>}
 <div className="six-surface border overflow-x-auto"><table className="w-full text-sm"><thead className="border-b six-border"><tr className="six-muted text-left"><th className="p-4">Learner</th><th className="p-4">Course</th><th className="p-4">Progress</th><th className="p-4">Status</th><th className="p-4">Enrolled</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{loading?<tr><td colSpan="6" className="p-10 text-center six-muted">Loading…</td></tr>:rows.length===0?<tr><td colSpan="6" className="p-10 text-center six-muted">No enrollments found.</td></tr>:rows.map(r=><tr key={r.id} className="border-b six-border last:border-0"><td className="p-4"><b>{r.learner_name}</b><div className="text-xs six-muted">{r.learner_email}</div></td><td className="p-4 font-medium">{r.course_title}</td><td className="p-4 min-w-[170px]"><div className="flex justify-between text-xs mb-1"><span>{Number(r.progress_percent||0).toFixed(0)}%</span></div><div className="h-2 rounded-full bg-gray-200 overflow-hidden"><div className="h-full six-progress" style={{width:`${Math.min(100,Math.max(0,Number(r.progress_percent||0)))}%`}}/></div></td><td className="p-4"><span className={`px-2.5 py-1 rounded-full text-xs ${statusMeta[r.status]?.[1]||'bg-gray-100'}`}>{statusMeta[r.status]?.[0]||r.status}</span></td><td className="p-4 text-xs six-muted">{new Date(r.enrolled_at).toLocaleDateString()}</td><td className="p-4 text-right">{can('enrollments.cancel')&&r.status==='active'&&<button onClick={()=>cancel(r.id)} className="p-2 six-hover rounded-lg text-red-600" title="Cancel"><Ban size={17}/></button>}</td></tr>)}</tbody></table></div>
 {open&&<Modal title="Enroll learners" onClose={()=>setOpen(false)}><form onSubmit={enroll} className="space-y-5"><label className="block"><span className="text-xs six-muted">Course</span><select required className="six-input w-full rounded-xl px-3 py-2.5 mt-1" value={selectedCourse} onChange={e=>setSelectedCourse(e.target.value)}><option value="">Select a published course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><div><div className="flex justify-between items-center mb-2"><span className="text-xs six-muted">Learners</span><button type="button" className="text-xs six-primary-text" onClick={()=>setSelected(learners.map(x=>x.id))}>Select all</button></div><div className="border six-border rounded-xl max-h-72 overflow-y-auto">{learners.map(l=><label key={l.id} className="flex gap-3 items-center p-3 border-b six-border last:border-0 six-hover"><input type="checkbox" checked={selected.includes(l.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,l.id]:s.filter(id=>id!==l.id))}/><span><b>{l.full_name}</b><span className="block text-xs six-muted">{l.email}</span></span></label>)}</div></div><div className="flex justify-end"><button disabled={saving||!selected.length||!selectedCourse} className="six-button rounded-xl px-5 py-2.5">{saving?'Enrolling…':`Enroll ${selected.length} learner${selected.length===1?'':'s'}`}</button></div></form></Modal>}</div>}
