import { Bell, LogOut, Menu, Search, X } from 'lucide-react'
import { useAuth } from '../../contexts/AuthContext'
import { useTheme } from '../../contexts/ThemeContext'
import { Link } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { api } from '../../services/api'

export default function Header({onMenu}) {
 const {user,logout}=useAuth(); const {mode}=useTheme(); const [q,setQ]=useState(''); const [courses,setCourses]=useState([])
 useEffect(()=>{if(q.trim().length<2){setCourses([]);return}; const t=setTimeout(()=>api.learnerCourses().then(x=>setCourses((Array.isArray(x)?x:(x.courses||[])).filter(c=>(c.title||'').toLowerCase().includes(q.toLowerCase())).slice(0,5)).catch(()=>{}),250); return()=>clearTimeout(t)},[q])
 const quick=[['Dashboard','/'],['My Learning','/learner'],['My Courses','/my-courses'],['My Progress','/learner/progress'],['Achievements','/learner/achievements'],['Certificates','/certificates'],['Content Library','/content'],['Analytics & Reports','/analytics']]
 const matches=quick.filter(x=>x[0].toLowerCase().includes(q.toLowerCase())).slice(0,5)
 return <header className="h-20 six-header flex items-center gap-4 px-4 sm:px-6"><button onClick={onMenu} className="lg:hidden p-2 rounded-xl six-hover"><Menu size={22}/></button><div className="hidden md:flex relative items-center gap-2 six-search rounded-xl px-3 h-11 w-full max-w-md"><Search size={18} className="six-muted"/><input value={q} onChange={e=>setQ(e.target.value)} className="bg-transparent outline-none w-full text-sm" placeholder="Search Sixele..."/><kbd className="hidden lg:block text-[10px] six-muted border six-border rounded px-1.5 py-0.5">/</kbd>{q&&<button onClick={()=>setQ('')} className="six-muted"><X size={15}/></button>}{q&&<div className="absolute top-13 left-0 right-0 z-50 six-surface border p-2 shadow-xl six-animate-pop">{matches.map(([label,to])=><Link key={to} onClick={()=>setQ('')} to={to} className="block px-3 py-2 rounded-lg six-hover text-sm">{label}</Link>)}{courses.map(c=><Link key={c.enrollment_id} onClick={()=>setQ('')} to={`/learn/${c.enrollment_id}`} className="block px-3 py-2 rounded-lg six-hover text-sm"><span className="six-primary-text">Course</span> · {c.title}</Link>)}{!matches.length&&!courses.length&&<div className="px-3 py-3 text-sm six-muted">No results found.</div>}</div>}</div><div className="ml-auto flex items-center gap-3"><button className="p-2.5 rounded-xl six-hover relative"><Bell size={20}/><span className="absolute top-2 right-2 w-2 h-2 rounded-full six-primary-bg"/></button><div className="flex items-center gap-3 pl-2"><div className="w-10 h-10 rounded-full six-primary-soft six-primary-text flex items-center justify-center font-semibold">{user?.name?.[0]||'S'}</div><div className="hidden sm:block"><div className="text-sm font-semibold">{user?.name}</div><div className="text-xs six-muted">{user?.email}</div></div><button onClick={logout} title="Sign out" className="p-2 rounded-xl six-hover six-muted"><LogOut size={18}/></button></div></div></header>
}
