import { useEffect, useMemo, useState } from 'react'
import { Copy, Edit3, Loader2, Plus, ShieldCheck, ToggleLeft, ToggleRight, Trash2, Users, X } from 'lucide-react'
import { api } from '../../services/api'
import { permissionCatalog } from '../../data/permissionCatalog'
import { usePermissions } from '../../contexts/PermissionContext'

const emptyForm = { name:'', description:'', permission_ids:[], scope:null, is_active:true }

export default function RoleManagement(){
 const {can}=usePermissions(); const [roles,setRoles]=useState([]); const [stats,setStats]=useState(null); const [show,setShow]=useState(false); const [editing,setEditing]=useState(null); const [form,setForm]=useState(emptyForm); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const [r,s]=await Promise.all([api.roles(),api.roleStats()]);setRoles(r);setStats(s)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const canCreate=can('roles.create'),canEdit=can('roles.edit'),canDelete=can('roles.delete')
 const openCreate=()=>{setEditing(null);setForm(emptyForm);setShow(true);setError('')}
 const openEdit=r=>{setEditing(r);setForm({name:r.name,description:r.description||'',permission_ids:r.permission_ids||[],scope:r.scope||null,is_active:r.is_active});setShow(true);setError('')}
 const toggle=p=>setForm(f=>({...f,permission_ids:f.permission_ids.includes(p)?f.permission_ids.filter(x=>x!==p):[...f.permission_ids,p]}))
 const save=async()=>{if(!form.name.trim())return setError('Role name is required');setBusy(true);setError('');try{if(editing) await api.updateRole(editing.id,{name:form.name,description:form.description,permission_ids:form.permission_ids,scope:form.scope,is_active:form.is_active});else await api.createRole(form);setShow(false);setNotice(editing?'Role updated':'Role created');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const duplicate=async id=>{try{await api.duplicateRole(id);setNotice('Role duplicated');await load()}catch(e){setError(e.message)}}
 const toggleStatus=async r=>{try{await api.updateRoleStatus(r.id,!r.is_active);setNotice(r.is_active?'Role deactivated':'Role activated');await load()}catch(e){setError(e.message)}}
 const remove=async r=>{if(!window.confirm(`Deactivate ${r.name}?`))return;try{await api.deleteRole(r.id);setNotice('Role deactivated');await load()}catch(e){setError(e.message)}}
 const totalPermissions=useMemo(()=>roles.reduce((n,r)=>n+(r.permission_ids?.length||0),0),[roles])
 return <div className="space-y-6">
  <div className="flex flex-col xl:flex-row xl:items-end justify-between gap-4"><div><div className="text-sm six-primary-text font-semibold">Administration</div><h1 className="text-3xl font-bold mt-1">Roles & Permissions</h1><p className="six-muted mt-1">Manage dynamic roles using the backend permission catalog.</p></div>{canCreate&&<button onClick={openCreate} className="inline-flex items-center justify-center gap-2 px-4 h-11 rounded-xl six-button font-semibold"><Plus size={18}/> Create role</button>}</div>
  {(error||notice)&&<div className={`rounded-xl border p-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'six-border'}`}>{error||notice}<button onClick={()=>{setError('');setNotice('')}} className="float-right"><X size={16}/></button></div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[['Total roles',stats?.total_roles??'—'],['Active roles',stats?.active_roles??'—'],['Custom roles',stats?.custom_roles??'—'],['Permission links',totalPermissions]].map(([l,v])=><div className="six-surface border p-5" key={l}><div className="text-sm six-muted">{l}</div><div className="text-2xl font-bold mt-2">{v}</div></div>)}</div>
  {loading?<div className="six-surface border p-10 text-center six-muted"><Loader2 className="animate-spin mx-auto"/></div>:<div className="grid gap-4">{roles.map(r=><div key={r.id} className="six-surface border p-5"><div className="flex flex-col lg:flex-row lg:items-center gap-4"><div className="w-11 h-11 rounded-xl six-primary-soft six-primary-text flex items-center justify-center"><ShieldCheck size={21}/></div><div className="flex-1"><div className="flex items-center gap-2"><div className="font-semibold text-lg">{r.name}</div><span className={`text-xs px-2 py-1 rounded-full ${r.is_active?'six-primary-soft six-primary-text':'bg-gray-100 text-gray-500'}`}>{r.is_active?'Active':'Inactive'}</span>{r.is_system&&<span className="text-xs px-2 py-1 rounded-full bg-gray-100 text-gray-600">System</span>}</div><div className="text-sm six-muted mt-1">{r.description||'No description'}</div><div className="flex flex-wrap gap-2 mt-3">{(r.permission_ids||[]).slice(0,6).map(p=><span key={p} className="text-xs px-2 py-1 rounded-lg" style={{background:'var(--hover)',color:'var(--muted)'}}>{p}</span>)}{(r.permission_ids||[]).length>6&&<span className="text-xs six-muted">+{r.permission_ids.length-6} more</span>}</div></div><div className="flex items-center gap-4 text-sm six-muted"><span className="flex items-center gap-1"><Users size={16}/>{r.user_count??0}</span>{!r.is_system&&<div className="flex gap-1">{canEdit&&<button onClick={()=>openEdit(r)} title="Edit" className="p-2 rounded-lg six-hover"><Edit3 size={17}/></button>}{canCreate&&<button onClick={()=>duplicate(r.id)} title="Duplicate" className="p-2 rounded-lg six-hover"><Copy size={17}/></button>}{canEdit&&<button onClick={()=>toggleStatus(r)} title={r.is_active?'Deactivate':'Activate'} className="p-2 rounded-lg six-hover">{r.is_active?<ToggleRight size={20}/>:<ToggleLeft size={20}/>}</button>}{canDelete&&<button onClick={()=>remove(r)} title="Deactivate" className="p-2 rounded-lg six-hover text-red-600"><Trash2 size={17}/></button>}</div>}</div></div></div>)}</div>}
  {show&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><div className="six-surface border w-full max-w-3xl max-h-[90vh] overflow-y-auto p-6"><div className="flex justify-between items-start"><div><h2 className="text-2xl font-bold">{editing?'Edit role':'Create role'}</h2><p className="text-sm six-muted mt-1">Choose permissions from the same catalog enforced by the API.</p></div><button onClick={()=>setShow(false)}><X/></button></div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 text-red-700 text-sm p-3">{error}</div>}<div className="grid md:grid-cols-2 gap-4 mt-6"><div><label className="text-sm font-medium">Role name</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="six-input w-full h-11 mt-2 px-3 rounded-xl outline-none"/></div><div><label className="text-sm font-medium">Description</label><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="six-input w-full h-11 mt-2 px-3 rounded-xl outline-none"/></div></div><div className="mt-6 space-y-5">{permissionCatalog.map(g=><div key={g.group}><div className="font-semibold mb-2">{g.group}</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-1">{g.items.map(p=><label key={p} className="flex items-center gap-2 text-sm p-2 rounded-lg six-hover"><input type="checkbox" checked={form.permission_ids.includes(p)} onChange={()=>toggle(p)}/><span>{p}</span></label>)}</div></div>)}</div><div className="flex justify-end gap-3 mt-7"><button onClick={()=>setShow(false)} className="px-4 h-11 rounded-xl border six-border">Cancel</button><button disabled={busy} onClick={save} className="px-4 h-11 rounded-xl six-button font-semibold flex items-center gap-2">{busy&&<Loader2 size={17} className="animate-spin"/>}{editing?'Save changes':'Create role'}</button></div></div></div>}
 </div>
}
