import { useEffect, useMemo, useState } from 'react'
import { Award, CheckCircle2, Edit3, Plus, RotateCcw, Search, ShieldOff, Trash2, X } from 'lucide-react'
import { api } from '../../services/api'

const emptyTemplate={name:'',description:'',title:'Certificate of Completion',issuer_name:'Sixele LMS',body_text:'This certificate is awarded for successful completion of the course.',signature_name:'',signature_title:'',is_active:true}
const fmt=v=>v?new Date(v).toLocaleDateString():''

export default function AdminCertificates(){
 const [certs,setCerts]=useState([]),[templates,setTemplates]=useState([]),[learners,setLearners]=useState([]),[enrollments,setEnrollments]=useState([])
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all')
 const [tab,setTab]=useState('certificates'),[showTemplate,setShowTemplate]=useState(false),[template,setTemplate]=useState(emptyTemplate),[editing,setEditing]=useState(null)
 const [issueOpen,setIssueOpen]=useState(false),[issue,setIssue]=useState({enrollment_id:'',template_id:'',force_override:false,override_reason:''})
 const [revoke,setRevoke]=useState(null),[busy,setBusy]=useState(false)
 const load=async()=>{setLoading(true);setError('');try{const [c,t,u,e]=await Promise.all([api.certificates(),api.certificateTemplates(),api.users({active:true}),api.adminEnrollments()]);setCerts(c);setTemplates(t);setLearners(u.filter(x=>x.is_learner||x.role_names?.some(r=>String(r).toLowerCase().includes('learner'))));setEnrollments(e)}catch(err){setError(err.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>certs.filter(c=>(status==='all'||c.status===status)&&`${c.learner_name} ${c.course_title} ${c.certificate_number}`.toLowerCase().includes(query.toLowerCase())),[certs,status,query])
 const saveTemplate=async()=>{setBusy(true);setError('');try{if(editing){await api.updateCertificateTemplate(editing,template)}else{await api.createCertificateTemplate(template)}setShowTemplate(false);setEditing(null);setTemplate(emptyTemplate);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const deleteTemplate=async id=>{if(!confirm('Delete this certificate template?'))return;try{await api.deleteCertificateTemplate(id);await load()}catch(e){setError(e.message)}}
 const doIssue=async()=>{setBusy(true);setError('');try{await api.issueCertificate({...issue,template_id:issue.template_id||null,override_reason:issue.override_reason||null});setIssueOpen(false);setIssue({enrollment_id:'',template_id:'',force_override:false,override_reason:''});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const doRevoke=async()=>{setBusy(true);try{await api.revokeCertificate(revoke.id,revoke.reason);setRevoke(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="space-y-6">
  <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4"><div><h1 className="text-2xl font-bold">Certificate Administration</h1><p className="six-muted mt-1">Issue, revoke and manage certificate templates.</p></div><button className="six-button px-4 py-2.5 rounded-xl inline-flex items-center gap-2" onClick={()=>setIssueOpen(true)}><Award size={17}/> Issue certificate</button></div>
  {error&&<div className="p-3 rounded-xl border border-red-200 bg-red-50 text-red-700 text-sm">{error}</div>}
  <div className="flex gap-2 border-b six-border"><button onClick={()=>setTab('certificates')} className={`px-4 py-2.5 text-sm border-b-2 ${tab==='certificates'?'border-[var(--primary)] six-primary-text':'border-transparent six-muted'}`}>Certificates</button><button onClick={()=>setTab('templates')} className={`px-4 py-2.5 text-sm border-b-2 ${tab==='templates'?'border-[var(--primary)] six-primary-text':'border-transparent six-muted'}`}>Templates</button></div>
  {tab==='certificates'?<>
   <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[['Issued',certs.filter(x=>x.status==='issued')],['Revoked',certs.filter(x=>x.status==='revoked')],['Templates',templates],['PDF ready',certs.filter(x=>x.pdf_generated)]].map(([label,list])=><div className="six-surface border p-5" key={label}><div className="text-sm six-muted">{label}</div><div className="text-2xl font-bold mt-2">{list.length}</div></div>)}</div>
   <div className="six-surface border p-4 flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-3 six-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} className="six-input w-full rounded-xl pl-9 pr-3 py-2.5" placeholder="Search learner, course or certificate number"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="six-input rounded-xl px-3 py-2.5"><option value="all">All statuses</option><option value="issued">Issued</option><option value="revoked">Revoked</option></select></div>
   <div className="six-surface border overflow-x-auto">{loading?<div className="p-10 text-center six-muted">Loading certificates…</div>:<table className="w-full text-sm"><thead><tr className="border-b six-border text-left six-muted"><th className="p-4">Learner</th><th className="p-4">Course</th><th className="p-4">Certificate</th><th className="p-4">Issued</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{filtered.map(c=><tr className="border-b six-border last:border-0" key={c.id}><td className="p-4 font-medium">{c.learner_name}</td><td className="p-4">{c.course_title}</td><td className="p-4 font-mono text-xs">{c.certificate_number}</td><td className="p-4">{fmt(c.issued_at)}</td><td className="p-4"><span className={`px-2 py-1 rounded-full text-xs ${c.status==='issued'?'bg-green-100 text-green-700':'bg-gray-100 text-gray-600'}`}>{c.status}</span></td><td className="p-4">{c.status==='issued'&&<button onClick={()=>setRevoke({id:c.id,reason:''})} className="px-3 py-1.5 rounded-lg border six-border text-xs inline-flex items-center gap-1"><ShieldOff size={14}/> Revoke</button>}</td></tr>)}</tbody></table>}</div>
  </>:<div className="space-y-4"><div className="flex justify-end"><button onClick={()=>{setEditing(null);setTemplate(emptyTemplate);setShowTemplate(true)}} className="six-button px-4 py-2.5 rounded-xl inline-flex items-center gap-2"><Plus size={17}/> New template</button></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{templates.map(t=><div className="six-surface border p-5" key={t.id}><div className="flex justify-between gap-3"><div><h3 className="font-bold">{t.name}</h3><p className="text-xs six-muted mt-1">{t.title}</p></div><span className={`text-xs px-2 py-1 rounded-full ${t.is_active?'bg-green-100 text-green-700':'bg-gray-100 six-muted'}`}>{t.is_active?'Active':'Inactive'}</span></div><p className="text-sm six-muted mt-4 line-clamp-3">{t.body_text}</p><div className="flex gap-2 mt-5"><button onClick={()=>{setEditing(t.id);setTemplate({...t});setShowTemplate(true)}} className="px-3 py-2 rounded-lg border six-border text-sm inline-flex items-center gap-1"><Edit3 size={14}/> Edit</button><button onClick={()=>deleteTemplate(t.id)} className="px-3 py-2 rounded-lg border six-border text-sm inline-flex items-center gap-1"><Trash2 size={14}/> Delete</button></div></div>)}</div></div>}
  {showTemplate&&<Modal title={editing?'Edit certificate template':'New certificate template'} onClose={()=>setShowTemplate(false)}><TemplateForm value={template} onChange={setTemplate}/><div className="flex justify-end gap-2 mt-6"><button className="px-4 py-2 rounded-xl border six-border" onClick={()=>setShowTemplate(false)}>Cancel</button><button className="six-button px-4 py-2 rounded-xl" disabled={busy} onClick={saveTemplate}>{busy?'Saving…':'Save template'}</button></div></Modal>}
  {issueOpen&&<Modal title="Issue certificate" onClose={()=>setIssueOpen(false)}><label className="text-sm font-medium">Completed enrollment<select value={issue.enrollment_id} onChange={e=>setIssue({...issue,enrollment_id:e.target.value})} className="six-input w-full rounded-xl px-3 py-2.5 mt-1"><option value="">Select enrollment</option>{enrollments.map(e=><option key={e.id} value={e.id}>{e.learner_name||e.learner_id} — {e.course_title||e.course_id}</option>)}</select></label><label className="text-sm font-medium block mt-4">Template<select value={issue.template_id} onChange={e=>setIssue({...issue,template_id:e.target.value})} className="six-input w-full rounded-xl px-3 py-2.5 mt-1"><option value="">Use default active template</option>{templates.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="flex items-center gap-2 mt-4 text-sm"><input type="checkbox" checked={issue.force_override} onChange={e=>setIssue({...issue,force_override:e.target.checked})}/> Override completion eligibility</label>{issue.force_override&&<textarea value={issue.override_reason} onChange={e=>setIssue({...issue,override_reason:e.target.value})} className="six-input w-full rounded-xl p-3 mt-3" rows="3" placeholder="Required reason for override"/>}<div className="flex justify-end gap-2 mt-6"><button className="px-4 py-2 rounded-xl border six-border" onClick={()=>setIssueOpen(false)}>Cancel</button><button className="six-button px-4 py-2 rounded-xl" disabled={!issue.enrollment_id||busy} onClick={doIssue}>{busy?'Issuing…':'Issue'}</button></div></Modal>}
  {revoke&&<Modal title="Revoke certificate" onClose={()=>setRevoke(null)}><p className="text-sm six-muted">Revocation is recorded in the audit trail and the certificate will no longer verify as valid.</p><textarea value={revoke.reason} onChange={e=>setRevoke({...revoke,reason:e.target.value})} className="six-input w-full rounded-xl p-3 mt-4" rows="4" placeholder="Reason for revocation"/><div className="flex justify-end gap-2 mt-6"><button className="px-4 py-2 rounded-xl border six-border" onClick={()=>setRevoke(null)}>Cancel</button><button className="six-button px-4 py-2 rounded-xl" disabled={revoke.reason.trim().length<3||busy} onClick={doRevoke}>Revoke</button></div></Modal>}
 </div>
}
function TemplateForm({value,onChange}){const f=(k,v)=>onChange({...value,[k]:v});return <div className="grid md:grid-cols-2 gap-4">{[['name','Template name'],['title','Certificate title'],['issuer_name','Issuer name'],['signature_name','Signature name'],['signature_title','Signature title']].map(([k,l])=><label key={k} className="text-sm font-medium">{l}<input value={value[k]} onChange={e=>f(k,e.target.value)} className="six-input w-full rounded-xl px-3 py-2.5 mt-1"/></label>)}<label className="md:col-span-2 text-sm font-medium">Description<input value={value.description} onChange={e=>f('description',e.target.value)} className="six-input w-full rounded-xl px-3 py-2.5 mt-1"/></label><label className="md:col-span-2 text-sm font-medium">Certificate body<textarea value={value.body_text} onChange={e=>f('body_text',e.target.value)} rows="4" className="six-input w-full rounded-xl p-3 mt-1"/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.is_active} onChange={e=>f('is_active',e.target.checked)}/> Active template</label></div>}
function Modal({title,onClose,children}){return <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="six-surface border w-full max-w-2xl max-h-[90vh] overflow-y-auto"><div className="flex items-center justify-between p-5 border-b six-border"><h2 className="font-bold text-lg">{title}</h2><button onClick={onClose}><X size={20}/></button></div><div className="p-5">{children}</div></div></div>}
