import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Loader2 } from 'lucide-react'
import { useAuth } from '../../contexts/AuthContext'

export default function Register(){
 const {register}=useAuth(); const nav=useNavigate(); const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 const submit=async e=>{e.preventDefault();setError('');if(password!==confirm){setError('Passwords do not match');return}setBusy(true);try{await register(name,email,password);nav('/')}catch(err){setError(err.message)}finally{setBusy(false)}}
 return <div className="min-h-screen flex items-center justify-center p-6" style={{background:'var(--background)',color:'var(--text)'}}><div className="w-full max-w-md"><div className="text-center mb-8"><div className="text-4xl font-bold six-primary-text">Sixele</div><p className="six-muted mt-2">Create your LMS account</p></div><form onSubmit={submit} className="six-surface border p-8 shadow-xl"><h1 className="text-2xl font-bold">Create account</h1><p className="six-muted mt-1 mb-7">Your account will be created without a role until an administrator assigns one.</p>{error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 text-red-700 text-sm p-3">{error}</div>}<label className="text-sm font-medium">Full name</label><input value={name} onChange={e=>setName(e.target.value)} required minLength={2} className="six-input w-full mt-2 mb-5 h-12 px-4 rounded-xl outline-none"/><label className="text-sm font-medium">Email</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required className="six-input w-full mt-2 mb-5 h-12 px-4 rounded-xl outline-none"/><label className="text-sm font-medium">Password</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password" required minLength={8} className="six-input w-full mt-2 mb-5 h-12 px-4 rounded-xl outline-none"/><label className="text-sm font-medium">Confirm password</label><input value={confirm} onChange={e=>setConfirm(e.target.value)} type="password" required className="six-input w-full mt-2 mb-6 h-12 px-4 rounded-xl outline-none"/><button disabled={busy} className="w-full h-12 rounded-xl six-button font-semibold flex items-center justify-center gap-2">{busy&&<Loader2 size={18} className="animate-spin"/>}{busy?'Creating…':'Create account'}</button><p className="text-center text-sm six-muted mt-6">Already registered? <Link className="six-primary-text font-semibold" to="/login">Sign in</Link></p></form></div></div>
}
