import { useEffect, useMemo, useState } from 'react'
import { MessageSquare, Megaphone, Send, Search, CheckCircle2, Users, BookOpen, MoreHorizontal, RefreshCw, CheckCheck } from 'lucide-react'
import Tooltip from '../../components/common/Tooltip'
import { api } from '../../services/api'
import { usePermissions } from '../../contexts/PermissionContext'

export default function CommunicationCenter(){
 const {can}=usePermissions(); const [items,setItems]=useState([]); const [active,setActive]=useState(null); const [tab,setTab]=useState('all'); const [search,setSearch]=useState(''); const [draft,setDraft]=useState(''); const [announcement,setAnnouncement]=useState(false); const [courseId,setCourseId]=useState(''); const [courses,setCourses]=useState([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const data=await api.communications({type:tab==='all'?'':tab,search});const next=data.items||[];setItems(next);setActive(prev=>next.find(x=>x.id===prev?.id)||next[0]||null)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[tab,search])
 useEffect(()=>{(async()=>{try{const data=can('courses.view')?await api.courses({status:'published'}):await api.instructorCourses();setCourses(Array.isArray(data)?data:(data?.items||[]))}catch{}})()},[can])
 const unread=useMemo(()=>items.filter(x=>!x.is_read).length,[items])
 const markRead=async(item)=>{if(item.is_read)return;try{const updated=await api.markCommunicationRead(item.id);setItems(xs=>xs.map(x=>x.id===item.id?updated:x));setActive(updated)}catch{}}
 const send=async()=>{if(!draft.trim()||!active||saving)return;setSaving(true);try{const updated=await api.replyCommunication(active.id,draft.trim());setItems(xs=>xs.map(x=>x.id===updated.id?updated:x));setActive(updated);setDraft('')}catch(e){setError(e.message)}finally{setSaving(false)}}
 const createAnnouncement=async()=>{if(!draft.trim()||saving)return;setSaving(true);try{const created=await api.createCommunication({type:'announcement',title:'New course announcement',body:draft.trim(),course_id:courseId||null});setItems(xs=>[created,...xs]);setActive(created);setDraft('');setAnnouncement(false);setCourseId('')}catch(e){setError(e.message)}finally{setSaving(false)}}
 const resolve=async()=>{if(!active||saving)return;setSaving(true);try{const updated=await api.resolveCommunication(active.id);setItems(xs=>xs.map(x=>x.id===updated.id?updated:x));setActive(updated)}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <div className="space-y-5 six-animate-rise">
  <div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold six-body-text">Communication Center</h1>{unread>0&&<span className="six-primary-bg text-white text-[11px] px-2 py-0.5 rounded-full animate-pulse">{unread} unread</span>}</div><p className="six-muted text-sm mt-1">Real-time-ready course announcements, learner questions and instructor feedback.</p></div><div className="flex gap-2"><Tooltip text="Refresh conversations"><button className="p-2.5 rounded-xl six-hover" onClick={load}><RefreshCw size={17}/></button></Tooltip>{can('communications.create')&&<button className="six-button px-4 py-2.5 rounded-xl flex items-center gap-2" onClick={()=>{setAnnouncement(true);setDraft('')}}><Megaphone size={17}/> New announcement</button>}</div></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 text-red-700 text-sm px-4 py-3">{error}</div>}
  <div className="grid lg:grid-cols-[340px_1fr] gap-5 min-h-[620px]">
   <section className="six-surface overflow-hidden"><div className="p-4 border-b six-border"><div className="six-search rounded-xl flex items-center px-3 gap-2"><Search size={17} className="six-muted"/><input className="w-full bg-transparent outline-none py-2.5 text-sm" placeholder="Search conversations..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="flex gap-2 mt-3 flex-wrap">{[['all','All'],['announcement','Announcements'],['thread','Questions']].map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`px-3 py-1.5 rounded-lg text-xs ${tab===v?'six-primary-soft six-primary-text':'six-hover six-muted'}`}>{l}</button>)}</div></div>
   <div className="divide-y six-border max-h-[555px] overflow-y-auto">{loading?<div className="p-8 text-center six-muted">Loading conversations…</div>:items.length===0?<div className="p-8 text-center six-muted"><BookOpen className="mx-auto mb-3"/><p>No conversations found.</p></div>:items.map(item=><button key={item.id} onClick={()=>{setActive(item);markRead(item)}} className={`w-full text-left p-4 six-hover transition ${active?.id===item.id?'six-primary-soft/40':''}`}><div className="flex items-start gap-3"><div className={`w-9 h-9 rounded-xl grid place-items-center shrink-0 ${item.type==='announcement'?'six-primary-soft':'bg-slate-100'}`}>{item.type==='announcement'?<Megaphone size={17} className="six-primary-text"/>:<MessageSquare size={17} className="six-muted"/>}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><span className="font-semibold text-sm truncate">{item.title}</span>{!item.is_read&&<span className="w-2 h-2 rounded-full six-primary-bg mt-1.5 shrink-0 animate-pulse"/>}</div><p className="text-xs six-muted mt-1">{item.course_title||'General'} · {new Date(item.created_at).toLocaleDateString()}</p><p className="text-xs six-muted mt-2 line-clamp-2">{item.body}</p></div></div></button>)}</div></section>
   <section className="six-surface flex flex-col overflow-hidden">{active?<><div className="p-5 border-b six-border flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-xs six-muted mb-2">{active.type==='announcement'?<Megaphone size={14}/>:<MessageSquare size={14}/>} {active.type==='announcement'?'Announcement':'Learner question'} · {active.course_title||'General'}</div><h2 className="text-xl font-bold six-body-text">{active.title}</h2><p className="text-xs six-muted mt-1">{active.author_name} · {new Date(active.created_at).toLocaleString()}</p></div><div className="flex gap-1">{active.type==='thread'&&active.status!=='resolved'&&can('communications.manage')&&<Tooltip text="Resolve conversation"><button className="p-2 rounded-lg six-hover" onClick={resolve}><CheckCheck size={18}/></button></Tooltip>}<Tooltip text="More conversation actions"><button className="p-2 rounded-lg six-hover"><MoreHorizontal size={18}/></button></Tooltip></div></div><div className="flex-1 p-5 overflow-y-auto"><div className="rounded-2xl p-4 six-task-tip six-animate-pop"><p className="text-sm leading-6">{active.body}</p></div>{(active.replies||[]).length>0&&<div className="mt-6 space-y-4">{active.replies.map((r,i)=><div key={r.id||i} className="flex gap-3 six-animate-rise"><div className="w-8 h-8 rounded-full six-primary-soft grid place-items-center"><Users size={15} className="six-primary-text"/></div><div className="flex-1"><div className="text-xs font-semibold">{r.author_name||'User'}</div><div className="six-surface border six-border p-3 rounded-xl mt-1 text-sm">{r.body}</div><div className="text-[10px] six-muted mt-1">{r.created_at&&new Date(r.created_at).toLocaleString()}</div></div></div>)}</div>}{active.type==='announcement'&&<div className="mt-6 text-sm six-muted flex items-center gap-2"><CheckCircle2 size={17} className="six-primary-text"/> Announcement delivered to its audience</div>}{active.status==='resolved'&&<div className="mt-6 rounded-xl six-primary-soft p-3 text-sm six-primary-text">This conversation has been resolved.</div>}</div>{active.type==='thread'&&active.status!=='resolved'&&can('communications.create')&&<div className="p-4 border-t six-border"><div className="flex gap-2"><input className="six-input rounded-xl flex-1 px-4 py-3 text-sm outline-none" placeholder="Write a reply or feedback..." value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!e.shiftKey&&(e.preventDefault(),send())}/><Tooltip text="Send reply"><button className="six-button rounded-xl px-4 disabled:opacity-50" disabled={saving} onClick={send}><Send size={17}/></button></Tooltip></div><p className="text-[11px] six-muted mt-2">Press Enter to send. Keep feedback specific, constructive and tied to the task.</p></div>}</>:<div className="m-auto text-center six-muted"><BookOpen className="mx-auto mb-3"/><p>Select a conversation to view it.</p></div>}</section>
  </div>
  {announcement&&<div className="fixed inset-0 z-50 bg-black/30 grid place-items-center p-4"><div className="six-surface w-full max-w-lg p-5 six-animate-pop"><div className="flex justify-between items-center"><h3 className="font-bold text-lg">New announcement</h3><button className="six-muted" onClick={()=>setAnnouncement(false)}>✕</button></div><p className="text-sm six-muted mt-1">Publish a course-wide message for learners and instructors.</p>{courses.length>0&&<select className="six-input w-full rounded-xl p-3 mt-4 outline-none" value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">All / general audience</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select>}<textarea className="six-input w-full rounded-xl p-3 mt-4 min-h-36 outline-none" placeholder="Write your announcement..." value={draft} onChange={e=>setDraft(e.target.value)}/><div className="flex justify-end gap-2 mt-4"><button className="px-4 py-2 rounded-xl six-hover" onClick={()=>setAnnouncement(false)}>Cancel</button><button className="six-button px-4 py-2 rounded-xl disabled:opacity-50" disabled={saving||!draft.trim()} onClick={createAnnouncement}>{saving?'Publishing…':'Publish'}</button></div></div></div>}
 </div>
}
