import { useEffect,useMemo,useState } from 'react'
import { Bell, CheckCircle2, History, Send, Users, X } from 'lucide-react'
import { api } from '../../services/api'
const types=['system','enrollment','submission','grading','revision','assessment','completion','course','attendance']
export default function AdminNotifications(){const[users,setUsers]=useState([]),[courses,setCourses]=useState([]),[history,setHistory]=useState([]),[selected,setSelected]=useState([]),[form,setForm]=useState({title:'',message:'',notification_type:'system',course_id:'',action_url:''}),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(null)
 useEffect(()=>{Promise.all([api.users({active:true}),api.courses({status:'published'})]).then(([u,c])=>{setUsers(u);setCourses(c)}).catch(e=>setError(e.message))},[])
 const filtered=useMemo(()=>users.filter(u=>`${u.full_name||u.name||''} ${u.email||''}`.toLowerCase().includes(search.toLowerCase())),[users,search])
 const toggle=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]); const send=async()=>{setBusy(true);setError('');try{const data=await api.createNotification({...form,recipient_ids:selected,course_id:form.course_id||null,action_url:form.action_url||null});setSent(data.length);setHistory(h=>[{...form,count:data.length,at:new Date().toISOString()},...h]);setSelected([]);setForm({title:'',message:'',notification_type:'system',course_id:'',action_url:''})}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Notification Administration</h1><p className="six-muted mt-1">Send targeted in-app notifications to active users.</p></div>{error&&<div className="p-3 rounded-xl border border-red-200 bg-red-50 text-red-700 text-sm">{error}</div>}{sent!=null&&<div className="p-3 rounded-xl border border-green-200 bg-green-50 text-green-700 text-sm inline-flex items-center gap-2"><CheckCircle2 size={17}/> Notification sent to {sent} recipient{sent===1?'':'s'}.</div>}
 <div className="grid xl:grid-cols-[1.2fr_.8fr] gap-6"><section className="six-surface border p-5"><div className="flex items-center gap-2 mb-4"><Bell size={18} className="six-primary-text"/><h2 className="font-bold">Compose notification</h2></div><div className="grid md:grid-cols-2 gap-4"><label className="text-sm font-medium">Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="six-input w-full rounded-xl px-3 py-2.5 mt-1"/></label><label className="text-sm font-medium">Type<select value={form.notification_type} onChange={e=>setForm({...form,notification_type:e.target.value})} className="six-input w-full rounded-xl px-3 py-2.5 mt-1">{types.map(t=><option key={t}>{t}</option>)}</select></label><label className="md:col-span-2 text-sm font-medium">Message<textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})} rows="6" className="six-input w-full rounded-xl p-3 mt-1"/></label><label className="text-sm font-medium">Related course<select value={form.course_id} onChange={e=>setForm({...form,course_id:e.target.value})} className="six-input w-full rounded-xl px-3 py-2.5 mt-1"><option value="">None</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="text-sm font-medium">Action URL<input value={form.action_url} onChange={e=>setForm({...form,action_url:e.target.value})} className="six-input w-full rounded-xl px-3 py-2.5 mt-1" placeholder="/my-courses"/></label></div><div className="flex justify-between items-center mt-6"><span className="text-sm six-muted">{selected.length} recipient{selected.length===1?'':'s'} selected</span><button className="six-button px-4 py-2.5 rounded-xl inline-flex items-center gap-2" disabled={busy||!form.title||!form.message||!selected.length} onClick={send}><Send size={16}/>{busy?'Sending…':'Send notification'}</button></div></section>
 <section className="six-surface border p-5"><div className="flex items-center justify-between gap-3 mb-4"><div className="flex items-center gap-2"><Users size={18} className="six-primary-text"/><h2 className="font-bold">Recipients</h2></div><button onClick={()=>setSelected(selected.length===filtered.length?[]:filtered.map(u=>u.id))} className="text-sm six-primary-text">{selected.length===filtered.length?'Clear all':'Select all'}</button></div><input value={search} onChange={e=>setSearch(e.target.value)} className="six-input w-full rounded-xl px-3 py-2.5 mb-3" placeholder="Search active users"/><div className="max-h-[430px] overflow-y-auto space-y-1">{filtered.map(u=><label key={u.id} className="flex items-center gap-3 p-3 rounded-xl six-hover cursor-pointer"><input type="checkbox" checked={selected.includes(u.id)} onChange={()=>toggle(u.id)}/><div className="min-w-0"><div className="font-medium truncate">{u.full_name||u.name||'User'}</div><div className="text-xs six-muted truncate">{u.email}</div></div></label>)}</div></section></div>
 <section className="six-surface border p-5"><div className="flex items-center gap-2 mb-4"><History size={18}/><h2 className="font-bold">This session's send history</h2></div>{history.length===0?<p className="text-sm six-muted">Notifications sent during this session will appear here.</p>:<div className="space-y-2">{history.map((h,i)=><div key={i} className="flex justify-between gap-3 p-3 rounded-xl six-primary-soft"><span className="text-sm"><b>{h.title}</b> · {h.notification_type}</span><span className="text-xs six-muted">{h.count} recipients · {new Date(h.at).toLocaleTimeString()}</span></div>)}</div>}</section></div>}
