import { useEffect, useMemo, useState } from 'react'
import { ClipboardCheck, Plus, Save, Send, Archive, Trash2, FileText, Users, ChevronDown, ChevronRight } from 'lucide-react'
import { api } from '../../services/api'

const types=['practical_task','file_submission','project','checklist','simulation','written_response','evidence_submission','manual_assessment']
const submissionTypes=['text','file','checklist','evidence','none']
const blank={title:'',description:'',activity_type:'practical_task',submission_type:'text',instructions:'',materials:[],task_description:'',max_score:100,pass_mark:50,attempts_allowed:1,due_days:null,is_required:true,order:0}
function Modal({children,onClose}){return <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4" onMouseDown={onClose}><div className="six-surface w-full max-w-3xl max-h-[90vh] overflow-auto p-6" onMouseDown={e=>e.stopPropagation()}>{children}</div></div>}
export default function AssessmentManagement(){
 const [courses,setCourses]=useState([]),[courseId,setCourseId]=useState(''),[modules,setModules]=useState([]),[moduleId,setModuleId]=useState(''),[activities,setActivities]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState(blank),[modal,setModal]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[rubric,setRubric]=useState(null),[submissions,setSubmissions]=useState([])
 useEffect(()=>{api.courses({}).then(setCourses).catch(e=>setError(e.message))},[])
 useEffect(()=>{if(!courseId){setModules([]);return} api.modules(courseId).then(x=>{setModules(x);if(x[0])setModuleId(x[0].id)}).catch(e=>setError(e.message))},[courseId])
 useEffect(()=>{if(!courseId||!moduleId)return; loadActivities()},[courseId,moduleId])
 async function loadActivities(){setLoading(true);try{setActivities(await api.activities(courseId,moduleId))}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function openActivity(a){setSelected(a);setForm({...a,materials:(a.materials||[]).join('\n')});setRubric(null);setSubmissions([]);try{const [r,s]=await Promise.all([api.activityRubric(a.id).catch(()=>null),api.activitySubmissions(a.id).catch(()=>[])]);setRubric(r);setSubmissions(s)}catch(e){setError(e.message)}}
 function edit(a=null){setSelected(a);setForm(a?{...a,materials:(a.materials||[]).join('\n')}:blank);setModal(true)}
 async function save(){setLoading(true);setError('');try{const p={...form,materials:String(form.materials||'').split('\n').map(x=>x.trim()).filter(Boolean)};if(selected)await api.updateActivity(selected.id,p);else await api.createActivity(courseId,moduleId,p);setModal(false);await loadActivities()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function action(name,id){setLoading(true);try{await api[name](id);await loadActivities();if(selected?.id===id){const a=activities.find(x=>x.id===id);if(a)openActivity(a)}}catch(e){setError(e.message)}finally{setLoading(false)}}
 return <div className="p-4 lg:p-8 space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold six-body-text">Practical Activities & Assessment</h1><p className="six-muted text-sm">Create practical work, configure scoring, rubrics and review learner submissions.</p></div>{courseId&&moduleId&&<button className="six-button px-4 py-2 rounded-xl flex gap-2 items-center" onClick={()=>edit()}><Plus size={18}/> New Activity</button>}</div>
 {error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-sm">{error}</div>}
 <div className="six-surface p-4 grid md:grid-cols-2 gap-4"><label className="text-sm six-muted">Course<select className="six-input w-full rounded-xl px-3 py-2 mt-1" value={courseId} onChange={e=>{setCourseId(e.target.value);setModuleId('')}}><option value="">Select course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="text-sm six-muted">Module<select className="six-input w-full rounded-xl px-3 py-2 mt-1" value={moduleId} onChange={e=>setModuleId(e.target.value)} disabled={!courseId}><option value="">Select module</option>{modules.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label></div>
 {moduleId&&<div className="grid lg:grid-cols-[1fr_1.2fr] gap-5"><div className="six-surface divide-y six-border">{loading&&!activities.length?<div className="p-8 text-center six-muted">Loading...</div>:!activities.length?<div className="p-8 text-center six-muted">No activities in this module.</div>:activities.map(a=><button key={a.id} className="w-full text-left p-4 six-hover" onClick={()=>openActivity(a)}><div className="flex justify-between gap-3"><div><div className="font-semibold six-body-text">{a.title}</div><div className="text-xs six-muted mt-1">{a.activity_type} · {a.submission_type}</div></div><span className="text-xs px-2 py-1 rounded-full six-primary-soft six-primary-text">{a.status}</span></div></button>)}</div>
 <div className="six-surface p-5 min-h-[420px]">{!selected?<div className="h-full flex items-center justify-center six-muted"><ClipboardCheck className="mr-2"/>Select an activity</div>:<><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold six-body-text">{selected.title}</h2><p className="six-muted text-sm">{selected.description||'No description'}</p></div><div className="flex gap-2"><button className="px-3 py-2 border six-border rounded-lg" onClick={()=>edit(selected)}>Edit</button>{selected.status==='draft'?<button className="six-button px-3 py-2 rounded-lg" onClick={()=>action('publishActivity',selected.id)}>Publish</button>:<button className="px-3 py-2 border six-border rounded-lg" onClick={()=>action('archiveActivity',selected.id)}>Archive</button>}</div></div><div className="grid sm:grid-cols-4 gap-3 my-5">{[['Max score',selected.max_score],['Pass mark',`${selected.pass_mark}%`],['Attempts',selected.attempts_allowed],['Submissions',submissions.length]].map(x=><div className="p-3 rounded-xl bg-[var(--hover)]" key={x[0]}><div className="text-xs six-muted">{x[0]}</div><div className="font-bold six-body-text">{x[1]}</div></div>)}</div><div className="space-y-4"><h3 className="font-semibold six-body-text">Rubric</h3>{rubric?<div className="space-y-2">{rubric.criteria?.map(c=><div className="flex justify-between p-3 border six-border rounded-xl" key={c.id}><span>{c.name}</span><span className="six-muted">{c.max_score} pts</span></div>)}</div>:<p className="six-muted text-sm">No rubric configured.</p>}<h3 className="font-semibold six-body-text pt-3">Recent submissions</h3>{submissions.length?<div className="space-y-2">{submissions.slice(0,5).map(s=><div className="p-3 border six-border rounded-xl flex justify-between" key={s.id}><span className="text-sm">Learner {s.learner_id.slice(-8)} · Attempt {s.attempt_number}</span><span className="text-xs six-muted">{s.status}</span></div>)}</div>:<p className="six-muted text-sm">No submissions yet.</p>}</div></>}</div></div>}
 {modal&&<Modal onClose={()=>setModal(false)}><h2 className="text-xl font-bold six-body-text mb-5">{selected?'Edit activity':'Create activity'}</h2><div className="grid md:grid-cols-2 gap-4"><Field label="Title" value={form.title} onChange={v=>setForm({...form,title:v})}/><Field label="Activity type" select value={form.activity_type} options={types} onChange={v=>setForm({...form,activity_type:v})}/><Field label="Submission type" select value={form.submission_type} options={submissionTypes} onChange={v=>setForm({...form,submission_type:v})}/><Field label="Maximum score" type="number" value={form.max_score} onChange={v=>setForm({...form,max_score:Number(v)})}/><Field label="Pass mark (%)" type="number" value={form.pass_mark} onChange={v=>setForm({...form,pass_mark:Number(v)})}/><Field label="Attempts allowed" type="number" value={form.attempts_allowed} onChange={v=>setForm({...form,attempts_allowed:Number(v)})}/></div><label className="block text-sm six-muted mt-4">Description<textarea className="six-input w-full rounded-xl p-3 mt-1" rows="2" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="block text-sm six-muted mt-4">Instructions<textarea className="six-input w-full rounded-xl p-3 mt-1" rows="4" value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})}/></label><label className="block text-sm six-muted mt-4">Materials (one per line)<textarea className="six-input w-full rounded-xl p-3 mt-1" rows="3" value={form.materials} onChange={e=>setForm({...form,materials:e.target.value})}/></label><label className="flex gap-2 items-center mt-4 six-body-text"><input type="checkbox" checked={form.is_required} onChange={e=>setForm({...form,is_required:e.target.checked})}/> Required for completion</label><div className="flex justify-end gap-2 mt-6"><button className="px-4 py-2 border six-border rounded-xl" onClick={()=>setModal(false)}>Cancel</button><button className="six-button px-4 py-2 rounded-xl flex gap-2" onClick={save}><Save size={17}/> Save</button></div></Modal>}
 </div>
}
function Field({label,value,onChange,type='text',select,options=[]}){return <label className="text-sm six-muted">{label}{select?<select className="six-input w-full rounded-xl px-3 py-2 mt-1" value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select>:<input className="six-input w-full rounded-xl px-3 py-2 mt-1" type={type} value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>}
