import { useEffect,useMemo,useState } from 'react'
import { BookOpen, Download, RefreshCw, Search, History, CheckCircle2 } from 'lucide-react'
import { api } from '../../services/api'

export default function Gradebook(){
 const [courses,setCourses]=useState([]),[courseId,setCourseId]=useState(''),[data,setData]=useState(null),[search,setSearch]=useState(''),[weights,setWeights]=useState({activity:.30,assignment:.40,quiz:.30}),[selected,setSelected]=useState(null),[history,setHistory]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{api.courses({}).then(setCourses).catch(e=>setError(e.message))},[])
 async function load(){if(!courseId)return;setBusy(true);setError('');try{setData(await api.gradebook({...weights,course_id:courseId}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(courseId)load()},[courseId])
 const learners=useMemo(()=>data?.learners?.filter(x=>`${x.learner_name} ${x.email}`.toLowerCase().includes(search.toLowerCase()))||[],[data,search])
 async function showHistory(l){setSelected(l);try{const x=await api.gradeHistory(courseId,l.learner_id);setHistory(x.history||[])}catch(e){setError(e.message)}}
 function exportCsv(){if(!learners.length)return;const rows=[['Learner','Email','Overall %','Activities','Assignments','Quizzes'],...learners.map(l=>[l.learner_name,l.email,l.overall_percentage??'',l.category_scores?.activity??'',l.category_scores?.assignment??'',l.category_scores?.quiz??''])];const blob=new Blob([rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sixele-gradebook-${courseId}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <div className="p-4 lg:p-8 space-y-6">
  <div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-bold six-body-text">Gradebook</h1><p className="six-muted text-sm mt-1">Review weighted course grades, attempts and reassessment history.</p></div><div className="flex gap-2"><button onClick={exportCsv} disabled={!learners.length} className="px-4 py-2 border six-border rounded-xl flex gap-2"><Download size={17}/> Export</button><button onClick={load} disabled={!courseId||busy} className="six-button px-4 py-2 rounded-xl flex gap-2"><RefreshCw size={17}/> Refresh</button></div></div>
  {error&&<div className="p-3 rounded-xl bg-red-50 text-red-700">{error}</div>}
  <div className="six-surface p-4 grid lg:grid-cols-[1.5fr_1fr] gap-4"><label className="text-sm six-muted">Course<select className="six-input w-full rounded-xl px-3 py-2 mt-1" value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Select course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><div><div className="text-sm six-muted mb-1">Category weights</div><div className="grid grid-cols-3 gap-2">{Object.entries(weights).map(([k,v])=><label key={k} className="text-xs six-muted">{k}<input type="number" min="0" max="100" value={Math.round(v*100)} onChange={e=>setWeights(w=>({...w,[k]:Number(e.target.value)/100}))} className="six-input w-full rounded-lg px-2 py-2"/></label>)}</div></div></div>
  {data&&<><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[['Learners',learners.length],['Activities',data.categories.activity],['Assignments',data.categories.assignment],['Quizzes',data.categories.quiz]].map(x=><div className="six-surface p-4" key={x[0]}><div className="text-xs six-muted">{x[0]}</div><div className="text-2xl font-bold six-body-text">{x[1]}</div></div>)}</div><div className="six-surface p-4 flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 six-muted" size={18}/><input className="six-input w-full rounded-xl pl-10 py-2" placeholder="Search learner" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
  <div className="six-surface overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b six-border text-left six-muted"><th className="p-4">Learner</th><th className="p-4">Activities</th><th className="p-4">Assignments</th><th className="p-4">Quizzes</th><th className="p-4">Weighted grade</th><th className="p-4">History</th></tr></thead><tbody>{learners.map(l=><tr className="border-b six-border six-hover" key={l.learner_id}><td className="p-4"><div className="font-semibold six-body-text">{l.learner_name}</div><div className="text-xs six-muted">{l.email}</div></td><td className="p-4">{l.category_scores?.activity??'—'}%</td><td className="p-4">{l.category_scores?.assignment??'—'}%</td><td className="p-4">{l.category_scores?.quiz??'—'}%</td><td className="p-4 font-bold">{l.overall_percentage??'—'}%</td><td className="p-4"><button onClick={()=>showHistory(l)} className="px-3 py-2 border six-border rounded-lg flex gap-2"><History size={16}/> View</button></td></tr>)}</tbody></table></div></>}
  {selected&&<div className="fixed inset-0 z-50 bg-black/50 flex justify-end" onMouseDown={()=>setSelected(null)}><div className="w-full max-w-2xl h-full six-surface p-6 overflow-auto" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between"><div><h2 className="text-xl font-bold six-body-text">{selected.learner_name}</h2><p className="six-muted text-sm">Grade history and reassessment attempts</p></div><button onClick={()=>setSelected(null)}>✕</button></div><div className="mt-6 space-y-3">{history.map((h,i)=><div key={i} className="p-4 border six-border rounded-xl"><div className="flex justify-between gap-3"><div><div className="font-semibold six-body-text">{h.title}</div><div className="text-xs six-muted">{h.category} · Attempt #{h.attempt}</div></div><div className="text-right">{h.percentage!=null?<b>{h.percentage}%</b>:<span className="six-muted">Pending</span>}<div className="text-xs six-muted">{h.status}</div></div></div>{h.feedback&&<p className="text-sm six-muted mt-2">{h.feedback}</p>}</div>)}{!history.length&&<div className="p-8 text-center six-muted">No assessment history.</div>}</div></div></div>}
 </div>
}
