import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ClipboardCheck, FileText, RotateCcw, Search, X, RefreshCw, Award, AlertCircle } from 'lucide-react'
import { api } from '../../services/api'

const kindLabel = { activity:'Practical Activity', assignment:'Assignment / Project', quiz:'Assessment / Quiz' }
const statusLabel = { submitted:'Submitted', under_review:'Under Review', needs_manual_grading:'Needs Grading', revision_requested:'Revision Requested', passed:'Passed', failed:'Failed', graded:'Graded' }

function Stat({label,value,icon:Icon}){ return <div className="six-surface p-5 flex items-center gap-4"><div className="p-3 rounded-xl six-primary-soft six-primary-text"><Icon size={21}/></div><div><div className="text-2xl font-bold six-body-text">{value}</div><div className="text-sm six-muted">{label}</div></div></div> }

export default function GradingCenter(){
  const [items,setItems]=useState([]),[tab,setTab]=useState('all'),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[score,setScore]=useState(''),[feedback,setFeedback]=useState(''),[status,setStatus]=useState(''),[criterionScores,setCriterionScores]=useState([]),[rubric,setRubric]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const load=async()=>{setError('');try{const [a,q]=await Promise.all([api.pendingSubmissions(),api.pendingAssessments()]);const activity=(a||[]).map(x=>({...x,kind:'activity',item_id:x.submission_id,title:x.activity_title}));const quiz=(q||[]).map(x=>({...x,kind:'quiz',item_id:x.attempt_id,title:x.quiz_title}));
      // Assignment/project submissions are collected from courses visible to the instructor. This keeps the grading center aligned with course scope.
      let assignment=[]; try { const courses=await api.instructorCourses(); const list=Array.isArray(courses)?courses:[]; const chunks=await Promise.all(list.slice(0,50).map(async c=>{const as=await api.assignments(c.course_id); const arr=[]; for(const x of (as||[]).slice(0,50)){const subs=await api.assignmentSubmissions(x.id); for(const s of (subs||[])) if(['submitted','under_review'].includes(s.status)) arr.push({submission_id:s.id,assignment_id:x.id,course_id:c.course_id,course_title:c.title||'',learner_id:s.learner_id,learner_name:s.learner_name||s.learner_id,attempt_number:s.attempt_number,status:s.status,submitted_at:s.submitted_at,kind:'assignment',item_id:s.id,title:x.title,score:s.score,percentage:s.percentage,feedback:s.feedback,raw:s})} return arr})); assignment=chunks.flat() } catch(_){/* assignment discovery is best effort; other queues remain available */}
      setItems([...activity,...quiz,...assignment].sort((x,y)=>new Date(y.submitted_at)-new Date(x.submitted_at)))
    }catch(e){setError(e.message)} }
  useEffect(()=>{load()},[])
  const filtered=useMemo(()=>items.filter(x=>(tab==='all'||x.kind===tab)&&`${x.learner_name||''} ${x.title||''} ${x.course_title||''} ${x.status||''}`.toLowerCase().includes(search.toLowerCase())),[items,tab,search])
  const counts=useMemo(()=>({all:items.length,activity:items.filter(x=>x.kind==='activity').length,assignment:items.filter(x=>x.kind==='assignment').length,quiz:items.filter(x=>x.kind==='quiz').length}),[items])
  async function open(item){setSelected(item);setScore(item.score??'');setFeedback(item.feedback||'');setStatus('');setCriterionScores([]);setRubric(null);setError('');try{if(item.kind==='activity'){const r=await api.activityRubric(item.activity_id);setRubric(r);setCriterionScores((r.criteria||[]).map(c=>({criterion_id:c.id,score:''})))} }catch(_){}}
  async function act(action){if(!selected)return;setBusy(true);setError('');try{let x;if(action==='review') x=selected.kind==='activity'?await api.reviewSubmission(selected.item_id):await api.reviewAssignmentSubmission(selected.item_id); if(action==='grade'){const payload={score:Number(score),feedback,criterion_scores:criterionScores.filter(c=>c.score!==''),...(status?{status}: {})}; x=selected.kind==='activity'?await api.gradeSubmission(selected.item_id,payload):selected.kind==='assignment'?await api.gradeAssignmentSubmission(selected.item_id,payload):await api.gradeQuizAttempt(selected.item_id,{score:Number(score),feedback})} if(action==='revision') x=selected.kind==='activity'?await api.returnSubmission(selected.item_id,{feedback}):selected.kind==='assignment'?await api.returnAssignmentSubmission(selected.item_id,{feedback}):null; if(x){setSelected({...selected,...x,score:x.score,percentage:x.percentage,status:x.status,feedback:x.feedback});} await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const max=selected?.total_points||selected?.max_score||100
  const passed=selected?.percentage!=null && selected.percentage >= (selected.pass_mark??50)
  return <div className="p-4 lg:p-8 space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold six-body-text">Advanced Grading Center</h1><p className="six-muted text-sm mt-1">One workspace for practical work, assignments, projects, and manually graded assessments.</p></div><button onClick={load} className="px-4 py-2 border six-border rounded-xl flex gap-2 items-center"><RefreshCw size={17}/> Refresh</button></div>
    {error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 flex gap-2"><AlertCircle size={18}/>{error}</div>}
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Stat label="Awaiting grading" value={counts.all} icon={ClipboardCheck}/><Stat label="Practical activities" value={counts.activity} icon={FileText}/><Stat label="Assignments / projects" value={counts.assignment} icon={Award}/><Stat label="Assessments / quizzes" value={counts.quiz} icon={CheckCircle2}/></div>
    <div className="six-surface p-4 flex flex-wrap gap-3"><div className="relative flex-1 min-w-60"><Search className="absolute left-3 top-2.5 six-muted" size={18}/><input className="six-input w-full rounded-xl pl-10 pr-3 py-2" placeholder="Search learner, course or assessment" value={search} onChange={e=>setSearch(e.target.value)}/></div>{[['all','All'],['activity','Practical'],['assignment','Assignments'],['quiz','Assessments']].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`px-4 py-2 rounded-xl ${tab===k?'six-button':'border six-border'}`}>{l} <span className="ml-1 opacity-70">{counts[k]}</span></button>)}</div>
    <div className="six-surface overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b six-border text-left six-muted"><th className="p-4">Learner</th><th className="p-4">Type</th><th className="p-4">Assessment</th><th className="p-4">Course</th><th className="p-4">Attempt</th><th className="p-4">Status</th><th className="p-4">Submitted</th><th/></tr></thead><tbody>{filtered.map(x=><tr key={`${x.kind}-${x.item_id}`} className="border-b six-border six-hover"><td className="p-4 font-medium six-body-text">{x.learner_name||x.learner_id}</td><td className="p-4">{kindLabel[x.kind]}</td><td className="p-4">{x.title}</td><td className="p-4">{x.course_title}</td><td className="p-4">#{x.attempt_number||1}</td><td className="p-4"><span className="px-2 py-1 rounded-full six-primary-soft six-primary-text">{statusLabel[x.status]||x.status}</span></td><td className="p-4 six-muted">{x.submitted_at?new Date(x.submitted_at).toLocaleString():'—'}</td><td className="p-4"><button onClick={()=>open(x)} className="px-3 py-2 border six-border rounded-lg">Open</button></td></tr>)}{!filtered.length&&<tr><td colSpan="8" className="p-10 text-center six-muted">No grading items found.</td></tr>}</tbody></table></div>
    {selected&&<div className="fixed inset-0 z-50 bg-black/50 flex justify-end" onMouseDown={()=>setSelected(null)}><div className="w-full max-w-2xl h-full six-surface p-6 overflow-auto" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between gap-4"><div><div className="text-xs six-muted uppercase tracking-wide">{kindLabel[selected.kind]}</div><h2 className="text-xl font-bold six-body-text">{selected.title}</h2><p className="six-muted text-sm">{selected.learner_name||selected.learner_id} · {selected.course_title}</p></div><button onClick={()=>setSelected(null)}><X/></button></div>
      <div className="grid grid-cols-3 gap-3 my-6"><div className="p-4 rounded-xl bg-[var(--hover)]"><div className="text-xs six-muted">Status</div><div className="font-semibold">{statusLabel[selected.status]||selected.status}</div></div><div className="p-4 rounded-xl bg-[var(--hover)]"><div className="text-xs six-muted">Attempt</div><div className="font-semibold">#{selected.attempt_number||1}</div></div><div className="p-4 rounded-xl bg-[var(--hover)]"><div className="text-xs six-muted">Pass mark</div><div className="font-semibold">{selected.pass_mark??'—'}%</div></div></div>
      {selected.text_response&&<div className="mb-5"><div className="text-sm font-semibold six-body-text mb-2">Learner response</div><div className="p-4 rounded-xl border six-border whitespace-pre-wrap">{selected.text_response}</div></div>}
      {selected.answers&&<div className="mb-5"><div className="text-sm font-semibold six-body-text mb-2">Assessment answers</div><div className="space-y-2">{selected.answers.map((a,i)=><div key={i} className="p-3 rounded-xl border six-border"><span className="six-muted">Question {i+1}:</span> {Array.isArray(a.answer)?a.answer.join(', '):String(a.answer??'')}</div>)}</div></div>}
      {rubric&&<div className="mb-5"><div className="text-sm font-semibold six-body-text mb-2">Rubric: {rubric.name}</div><div className="space-y-3">{(rubric.criteria||[]).map((c,i)=><div key={c.id} className="p-3 rounded-xl border six-border grid grid-cols-[1fr_110px] gap-3 items-center"><div><div className="font-medium">{c.name}</div><div className="text-xs six-muted">{c.description} · Max {c.max_score}</div></div><input type="number" min="0" max={c.max_score} className="six-input rounded-lg px-3 py-2" placeholder="Score" value={criterionScores[i]?.score??''} onChange={e=>setCriterionScores(v=>v.map((z,j)=>j===i?{...z,criterion_id:c.id,score:e.target.value}:z))}/></div>)}</div></div>}
      <div className="space-y-4"><div><label className="text-sm six-muted">Score {selected.kind==='quiz'?`/ ${max}`:''}</label><input type="number" min="0" max={max} className="six-input w-full rounded-xl px-3 py-2 mt-1" value={score} onChange={e=>setScore(e.target.value)}/>{score!==''&&<div className="text-xs six-muted mt-1">Calculated percentage: {max?((Number(score)/Number(max))*100).toFixed(2):0}%</div>}</div><div><label className="text-sm six-muted">Feedback</label><textarea rows="5" className="six-input w-full rounded-xl p-3 mt-1" value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Give clear, constructive feedback..."/></div>{selected.kind!=='quiz'&&<div><label className="text-sm six-muted">Result status</label><select className="six-input w-full rounded-xl px-3 py-2 mt-1" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Auto-calculate from pass mark</option><option value="passed">Passed</option><option value="failed">Failed</option><option value="revision_requested">Request revision</option></select></div>}</div>
      <div className="flex flex-wrap gap-2 mt-6">{['submitted','revision_requested'].includes(selected.status)&&selected.kind!=='quiz'&&<button disabled={busy} onClick={()=>act('review')} className="px-4 py-2 border six-border rounded-xl">Start review</button>}<button disabled={busy||score===''||selected.kind==='quiz'&&score==='' } onClick={()=>act('grade')} className="six-button px-4 py-2 rounded-xl flex gap-2 items-center"><CheckCircle2 size={17}/> Save grade</button>{selected.kind!=='quiz'&&<button disabled={busy} onClick={()=>act('revision')} className="px-4 py-2 border six-border rounded-xl flex gap-2 items-center"><RotateCcw size={17}/> Return for revision</button>}</div>
      {selected.percentage!=null&&<div className={`mt-6 p-4 rounded-xl ${selected.passed?'six-primary-soft':'bg-red-50'}`}><div className="font-semibold">{selected.passed?'Passed':'Not passed'} · {selected.percentage}%</div><div className="text-sm six-muted mt-1">The recorded result is calculated by the backend using the configured maximum score and pass mark.</div></div>}
    </div></div>}
  </div>
}
