import { useEffect, useMemo, useState } from 'react'
import { BarChart3, BookOpen, Users, Award, ClipboardCheck, TrendingUp, Download, RefreshCw, Search, ShieldAlert, Send, Activity } from 'lucide-react'
import { api } from '../../services/api'

const fmt=n=>Number(n||0).toLocaleString()
function Stat({icon:Icon,label,value,sub}){return <div className="six-surface border rounded-2xl p-5"><div className="flex items-start justify-between"><div><div className="six-muted text-sm">{label}</div><div className="text-2xl font-bold mt-1">{value}</div>{sub&&<div className="six-muted text-xs mt-1">{sub}</div>}</div><div className="p-3 rounded-xl six-hover"><Icon className="six-primary-text" size={20}/></div></div></div>}
function Progress({value}){return <div className="flex items-center gap-2"><div className="h-2 flex-1 rounded-full bg-black/5 overflow-hidden"><div className="h-full six-primary-bg" style={{width:`${Math.min(100,Math.max(0,Number(value)||0))}%`}}/></div><span className="text-xs w-12 text-right">{Number(value||0).toFixed(1)}%</span></div>}
export default function Analytics(){
 const [engagement,setEngagement]=useState(null),[overview,setOverview]=useState(null),[courses,setCourses]=useState([]),[instructors,setInstructors]=useState([]),[learners,setLearners]=useState([]),[submissions,setSubmissions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('courses'),[courseStatus,setCourseStatus]=useState(''),[search,setSearch]=useState('')
 const load=async()=>{setLoading(true);try{const [o,c,i,l,s,e]=await Promise.all([api.reportOverview(),api.courseReports({status:courseStatus}),api.instructorReports(),api.learnerReports(),api.submissionReports(),api.engagementReports()]);setOverview(o);setCourses(c);setInstructors(i);setLearners(l);setSubmissions(s);setEngagement(e);setError('')}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[courseStatus])
 const filtered=useMemo(()=>{const q=search.toLowerCase(); if(tab==='engagement') return (engagement?.learners||[]).filter(x=>(x.learner_name+' '+x.email+' '+x.course_title).toLowerCase().includes(q)); if(tab==='courses') return courses.filter(x=>x.course_title.toLowerCase().includes(q)); if(tab==='instructors') return instructors.filter(x=>(x.instructor_name+' '+x.email).toLowerCase().includes(q)); if(tab==='learners') return learners.filter(x=>(x.learner_name+' '+x.email).toLowerCase().includes(q)); return submissions.filter(x=>(x.activity_title+' '+x.course_title+' '+x.learner_name).toLowerCase().includes(q))},[tab,search,courses,instructors,learners,submissions,engagement])
 const exportReport=async report=>{try{const r=await api.reportExports(report);const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`sixele-${report}-report.csv`;a.click();URL.revokeObjectURL(url)}catch(e){setError(e.message)}}
 if(loading&&!overview) return <div className="p-6 six-muted">Loading analytics…</div>
 return <div className="p-4 sm:p-6 space-y-5">
  <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="flex items-center gap-2"><BarChart3 className="six-primary-text"/><h1 className="text-2xl font-bold">Analytics & Reports</h1></div><p className="six-muted mt-1">Organization-wide learning, enrollment, assessment and completion insights.</p></div><button onClick={load} className="six-hover rounded-xl px-3 py-2 flex items-center gap-2"><RefreshCw size={17}/>Refresh</button></div>
  {error&&<div className="rounded-xl bg-red-50 text-red-700 p-3">{error}</div>}
  {overview&&<div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Stat icon={BookOpen} label="Courses" value={fmt(overview.courses)} sub={`${fmt(overview.published_courses)} published`}/><Stat icon={Users} label="Learners" value={fmt(overview.learners)} sub={`${fmt(overview.active_enrollments)} active enrollments`}/><Stat icon={TrendingUp} label="Completion rate" value={`${overview.completion_rate}%`} sub={`${overview.average_course_progress}% avg progress`}/><Stat icon={Award} label="Certificates" value={fmt(overview.certificates_issued)} sub={`${fmt(overview.certificates_revoked)} revoked`}/></div>}
  {overview&&<div className="grid lg:grid-cols-3 gap-4"><Stat icon={ClipboardCheck} label="Pending submissions" value={fmt(overview.submissions_pending)}/><Stat icon={BarChart3} label="Pending assessments" value={fmt(overview.assessments_pending)}/><Stat icon={TrendingUp} label="Completed enrollments" value={fmt(overview.completed_enrollments)} /></div>}
  <div className="six-surface border rounded-2xl p-4"><div className="flex flex-col lg:flex-row gap-3 lg:items-center"><div className="flex flex-wrap gap-2">{[['courses','Courses'],['instructors','Instructors'],['learners','Learners'],['submissions','Submissions'],['engagement','Engagement']].map(([v,l])=><button key={v} onClick={()=>{setTab(v);setSearch('')}} className={`px-4 py-2 rounded-xl text-sm ${tab===v?'six-button':'six-hover'}`}>{l}</button>)}</div><div className="flex gap-2 lg:ml-auto"><div className="relative"><Search className="absolute left-3 top-2.5 six-muted" size={17}/><input className="six-input pl-9" placeholder="Search report" value={search} onChange={e=>setSearch(e.target.value)}/></div>{tab==='courses'&&<select className="six-input" value={courseStatus} onChange={e=>setCourseStatus(e.target.value)}><option value="">All statuses</option><option value="draft">Draft</option><option value="setup">Setup</option><option value="review">Review</option><option value="published">Published</option><option value="archived">Archived</option></select>}{tab!=='engagement'&&<button onClick={()=>exportReport(tab)} className="six-hover rounded-xl px-3" title="Export CSV"><Download size={18}/></button>}</div></div></div>
  <div className="six-surface border rounded-2xl overflow-x-auto">
   {tab==='courses'&&<table className="w-full text-sm"><thead className="border-b six-border"><tr className="six-muted text-left"><th className="p-4">Course</th><th className="p-4">Enrollments</th><th className="p-4">Completion</th><th className="p-4">Avg progress</th><th className="p-4">Assessment</th><th className="p-4">Certificates</th></tr></thead><tbody>{filtered.map(x=><tr key={x.course_id} className="border-b six-border"><td className="p-4"><b>{x.course_title}</b><div className="text-xs six-muted">{x.status}</div></td><td className="p-4">{fmt(x.enrollments)}<div className="text-xs six-muted">{fmt(x.active_learners)} active</div></td><td className="p-4 w-48"><Progress value={x.completion_rate}/></td><td className="p-4 w-48"><Progress value={x.average_progress}/></td><td className="p-4">{x.average_assessment_score==null?'—':`${x.average_assessment_score}%`}<div className="text-xs six-muted">{x.assessment_attempts} attempts</div></td><td className="p-4">{fmt(x.certificates_issued)}</td></tr>)}</tbody></table>}
   {tab==='instructors'&&<table className="w-full text-sm"><thead className="border-b six-border"><tr className="six-muted text-left"><th className="p-4">Instructor</th><th className="p-4">Courses</th><th className="p-4">Learners</th><th className="p-4">Completed</th><th className="p-4">Pending work</th></tr></thead><tbody>{filtered.map(x=><tr key={x.instructor_id} className="border-b six-border"><td className="p-4"><b>{x.instructor_name}</b><div className="text-xs six-muted">{x.email}</div></td><td className="p-4">{fmt(x.assigned_courses)}</td><td className="p-4">{fmt(x.total_learners)}</td><td className="p-4">{fmt(x.completed_learners)}</td><td className="p-4">{fmt(x.pending_submissions+x.pending_assessments)}</td></tr>)}</tbody></table>}
   {tab==='learners'&&<table className="w-full text-sm"><thead className="border-b six-border"><tr className="six-muted text-left"><th className="p-4">Learner</th><th className="p-4">Enrollments</th><th className="p-4">Active</th><th className="p-4">Completed</th><th className="p-4">Avg progress</th><th className="p-4">Certificates</th></tr></thead><tbody>{filtered.map(x=><tr key={x.learner_id} className="border-b six-border"><td className="p-4"><b>{x.learner_name}</b><div className="text-xs six-muted">{x.email}</div></td><td className="p-4">{fmt(x.enrollments)}</td><td className="p-4">{fmt(x.active_enrollments)}</td><td className="p-4">{fmt(x.completed_courses)}</td><td className="p-4 w-48"><Progress value={x.average_progress}/></td><td className="p-4">{fmt(x.certificates_issued)}</td></tr>)}</tbody></table>}
   {tab==='engagement'&&engagement&&<div className="p-5 space-y-5">
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
     {[['Healthy',engagement.healthy,'text-green-700'],['Watch',engagement.watch,'text-amber-700'],['High risk',engagement.high,'text-orange-700'],['Critical',engagement.critical,'text-red-700']].map(([l,v,c])=><div key={l} className="border six-border rounded-xl p-4"><div className="text-xs six-muted">{l}</div><div className={`text-2xl font-bold mt-1 ${c}`}>{fmt(v)}</div></div>)}
    </div>
    <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b six-border"><tr className="six-muted text-left"><th className="p-3">Learner</th><th className="p-3">Course</th><th className="p-3">Progress</th><th className="p-3">Last activity</th><th className="p-3">Risk</th><th className="p-3"></th></tr></thead><tbody>{filtered.map(x=><tr key={x.enrollment_id} className="border-b six-border"><td className="p-3"><b>{x.learner_name}</b><div className="text-xs six-muted">{x.email}</div></td><td className="p-3">{x.course_title}</td><td className="p-3">{x.progress_percent}%</td><td className="p-3">{x.last_activity_at?new Date(x.last_activity_at).toLocaleDateString():'No activity'}<div className="text-xs six-muted">{x.days_inactive} days inactive</div></td><td className="p-3 capitalize">{x.risk_level}</td><td className="p-3 text-right">{x.risk_level!=='healthy'&&<button onClick={async()=>{try{await api.sendLearnerNudge(x.enrollment_id)}catch(e){setError(e.message)}}} className="six-hover rounded-lg px-3 py-2 inline-flex items-center gap-2" title="Send learner reminder"><Send size={15}/>Nudge</button>}</td></tr>)}</tbody></table></div>
   </div>}
   {tab==='submissions'&&<table className="w-full text-sm"><thead className="border-b six-border"><tr className="six-muted text-left"><th className="p-4">Learner</th><th className="p-4">Activity</th><th className="p-4">Course</th><th className="p-4">Status</th><th className="p-4">Score</th><th className="p-4">Submitted</th></tr></thead><tbody>{filtered.slice(0,500).map(x=><tr key={x.submission_id} className="border-b six-border"><td className="p-4">{x.learner_name}</td><td className="p-4">{x.activity_title}</td><td className="p-4">{x.course_title}</td><td className="p-4 capitalize">{x.status.replaceAll('_',' ')}</td><td className="p-4">{x.percentage==null?'—':`${x.percentage}%`}</td><td className="p-4">{x.submitted_at?new Date(x.submitted_at).toLocaleDateString():'—'}</td></tr>)}</tbody></table>}
   {!filtered.length&&<div className="p-10 text-center six-muted">No report records found.</div>}
  </div>
 </div>
}