import { Check, Moon, Sun, Monitor, PanelLeft, Square, SlidersHorizontal } from 'lucide-react'
import { useTheme } from '../../contexts/ThemeContext'
const Choice = ({active,onClick,children}) => <button onClick={onClick} className={`p-3 rounded-xl border text-left transition ${active?'border-[var(--primary)] ring-2 ring-[var(--primary)]/15':'six-border six-hover'}`}>{children}</button>
export default function Appearance(){
 const {theme,setTheme,mode,setMode,density,setDensity,radius,setRadius,sidebarStyle,setSidebarStyle,sidebarCollapsed,setSidebarCollapsed,themes}=useTheme()
 return <div className="space-y-7">
  <div><div className="text-sm six-primary-text font-semibold">Settings</div><h1 className="text-3xl font-bold mt-1">Appearance</h1><p className="six-muted mt-1">Customize the Sixele LMS workspace without changing its functionality or branding rules.</p></div>
  <section className="six-surface border p-6"><div className="flex items-start gap-3"><SlidersHorizontal className="six-primary-text"/><div><h2 className="text-lg font-bold">Themes</h2><p className="text-sm six-muted">Sixele Red is the official default. Other themes change the interface palette only.</p></div></div>
   <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-6">{Object.entries(themes).map(([key,t])=><Choice key={key} active={theme===key} onClick={()=>setTheme(key)}><div className="h-16 rounded-lg overflow-hidden flex" style={{background:t.background}}><div className="w-1/3" style={{background:t.sidebar}}/><div className="flex-1 p-3"><div className="h-2 w-2/3 rounded bg-black/10"/><div className="h-2 w-1/2 rounded bg-black/10 mt-2"/><div className="w-8 h-2 rounded mt-3" style={{background:t.primary}}/></div></div><div className="flex items-center justify-between mt-3"><div><div className="font-semibold">{t.name}</div><div className="text-xs six-muted">{t.description}</div></div>{theme===key&&<Check size={19} className="six-primary-text"/>}</div></Choice>)}</div>
  </section>
  <section className="six-surface border p-6"><h2 className="text-lg font-bold">Display mode</h2><div className="grid grid-cols-3 gap-3 mt-4"><Choice active={mode==='light'} onClick={()=>setMode('light')}><Sun size={18}/><div className="font-medium mt-2">Light</div></Choice><Choice active={mode==='dark'} onClick={()=>setMode('dark')}><Moon size={18}/><div className="font-medium mt-2">Dark</div></Choice><Choice active={mode==='system'} onClick={()=>setMode('system')}><Monitor size={18}/><div className="font-medium mt-2">System</div></Choice></div></section>
  <section className="six-surface border p-6"><h2 className="text-lg font-bold">Workspace layout</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-4"><Choice active={density==='comfortable'} onClick={()=>setDensity('comfortable')}><div className="font-medium">Comfortable</div><div className="text-xs six-muted mt-1">More breathing room</div></Choice><Choice active={density==='compact'} onClick={()=>setDensity('compact')}><div className="font-medium">Compact</div><div className="text-xs six-muted mt-1">More information per screen</div></Choice><Choice active={radius==='rounded'} onClick={()=>setRadius('rounded')}><Square size={18}/><div className="font-medium mt-2">Rounded</div></Choice><Choice active={radius==='standard'} onClick={()=>setRadius('standard')}><Square size={18}/><div className="font-medium mt-2">Standard</div></Choice></div><div className="grid sm:grid-cols-2 gap-3 mt-3"><Choice active={radius==='sharp'} onClick={()=>setRadius('sharp')}><div className="font-medium">Sharp cards</div><div className="text-xs six-muted mt-1">Minimal corner radius</div></Choice><Choice active={sidebarStyle==='solid'} onClick={()=>setSidebarStyle('solid')}><div className="font-medium">Solid sidebar</div><div className="text-xs six-muted mt-1">Strong navigation contrast</div></Choice><Choice active={sidebarStyle==='soft'} onClick={()=>setSidebarStyle('soft')}><div className="font-medium">Soft sidebar</div><div className="text-xs six-muted mt-1">Softer navigation treatment</div></Choice><Choice active={sidebarCollapsed} onClick={()=>setSidebarCollapsed(!sidebarCollapsed)}><PanelLeft size={18}/><div className="font-medium mt-2">{sidebarCollapsed?'Collapsed':'Expanded'} sidebar</div></Choice></div></section>
 </div>
}
