from motor.motor_asyncio import AsyncIOMotorClient
from app.core.config import settings

client = AsyncIOMotorClient(settings.mongo_url)
db = client[settings.db_name]

async def init_db():
    await db.users.create_index("email", unique=True)
    await db.roles.create_index("name", unique=True)
    await db.audit_logs.create_index("created_at")
    await db.audit_logs.create_index([("actor_id", 1), ("created_at", -1)])
    await db.audit_logs.create_index([("resource", 1), ("created_at", -1)])
    await db.audit_logs.create_index([("action", 1), ("created_at", -1)])
    await db.audit_logs.create_index("request_id")
    await db.notifications.create_index([("recipient_id", 1), ("created_at", -1)])
    await db.notifications.create_index([("recipient_id", 1), ("is_read", 1)])
    await db.notification_preferences.create_index("user_id", unique=True)
    await db.courses.create_index("status")
    await db.course_versions.create_index([("course_id", 1), ("version_number", -1)], unique=True)
    await db.course_versions.create_index([("course_id", 1), ("status", 1)])
    await db.courses.create_index("title")
    await db.courses.create_index("instructor_ids")
    await db.modules.create_index([("course_id", 1), ("order", 1)])
    await db.lessons.create_index([("module_id", 1), ("order", 1)])
    await db.resources.create_index("module_id")
    await db.activities.create_index([("course_id", 1), ("module_id", 1), ("order", 1)])
    await db.activities.create_index("status")
    await db.rubrics.create_index("activity_id", unique=True)
    await db.rubric_criteria.create_index([("rubric_id", 1), ("order", 1)])
    await db.submissions.create_index([("activity_id", 1), ("learner_id", 1), ("attempt_number", -1)])
    await db.submissions.create_index([("activity_id", 1), ("status", 1)])
    await db.submissions.create_index("learner_id")
    await db.activity_progress.create_index([("activity_id", 1), ("learner_id", 1)], unique=True)
    await db.quizzes.create_index([("course_id", 1), ("module_id", 1), ("order", 1)])
    await db.quizzes.create_index("status")
    await db.quiz_questions.create_index([("quiz_id", 1), ("order", 1)])
    await db.quiz_attempts.create_index([("quiz_id", 1), ("learner_id", 1), ("attempt_number", -1)])
    await db.quiz_attempts.create_index([("quiz_id", 1), ("status", 1)])
    await db.quiz_attempts.create_index("learner_id")
    await db.enrollments.create_index([("learner_id", 1), ("course_id", 1)], unique=True)
    await db.enrollments.create_index([("course_id", 1), ("status", 1)])
    await db.submissions.create_index([("course_id", 1), ("status", 1), ("submitted_at", -1)])
    await db.quiz_attempts.create_index([("quiz_id", 1), ("status", 1), ("submitted_at", -1)])
    await db.lesson_progress.create_index([("lesson_id", 1), ("learner_id", 1)], unique=True)
    await db.lesson_progress.create_index([("course_id", 1), ("learner_id", 1)])
    await db.certificate_templates.create_index("name", unique=True)
    await db.certificate_templates.create_index("is_active")
    await db.certificates.create_index("certificate_number", unique=True)
    await db.certificates.create_index("enrollment_id", unique=True)
    await db.certificates.create_index([("automatic", 1), ("issued_at", -1)])
    await db.certificates.create_index([("learner_id", 1), ("issued_at", -1)])
    await db.certificates.create_index([("course_id", 1), ("status", 1)])
    await db.certificates.create_index("pdf_path")
    await db.enrollments.create_index([("course_id", 1), ("status", 1), ("progress_percent", 1)])
    await db.enrollments.create_index([("course_id", 1), ("learner_id", 1), ("status", 1)])
    await db.courses.create_index([("status", 1), ("visibility", 1), ("category", 1), ("level", 1)])
    await db.submissions.create_index([("course_id", 1), ("status", 1), ("submitted_at", -1)])
    await db.users.create_index("full_name")
    await db.content_library.create_index([("course_id", 1), ("created_at", -1)])
    await db.content_library.create_index([("folder", 1), ("status", 1)])
    await db.content_library.create_index("content_type")
    await db.content_library.create_index("uploaded_by")
    await db.system_settings.create_index("key", unique=True)
    await db.system_settings.create_index([("category", 1), ("key", 1)])
    await db.enrollments.create_index([("learner_id", 1), ("status", 1), ("enrolled_at", -1)])
    await db.lesson_progress.create_index([("learner_id", 1), ("course_id", 1), ("completed", 1)])
    await db.activity_progress.create_index([("learner_id", 1), ("status", 1)])
    await db.assignments.create_index([("course_id", 1), ("assignment_type", 1), ("order", 1)])
    await db.assignments.create_index([("course_id", 1), ("status", 1)])
    await db.assignments.create_index("rubric_id")
    await db.assignment_submissions.create_index([("assignment_id", 1), ("learner_id", 1), ("attempt_number", -1)])
    await db.assignment_submissions.create_index([("course_id", 1), ("status", 1), ("submitted_at", -1)])
    await db.assignment_submissions.create_index("learner_id")
    await db.assignment_progress.create_index([("assignment_id", 1), ("learner_id", 1)], unique=True)
    await db.assignment_progress.create_index([("learner_id", 1), ("status", 1)])
    await db.quiz_attempts.create_index([("learner_id", 1), ("status", 1), ("submitted_at", -1)])
    await db.notifications.create_index([("recipient_id", 1), ("is_read", 1), ("created_at", -1)])
    await db.email_outbox.create_index([("status", 1), ("next_attempt_at", 1), ("created_at", 1)])
    await db.email_outbox.create_index([("recipient_id", 1), ("created_at", -1)])
    await db.email_outbox.create_index("notification_id")
    await db.scheduled_jobs.create_index("job_name", unique=True)
    await db.scheduled_jobs.create_index("last_run_at")
    await db.job_leases.create_index("job_name", unique=True)
    await db.job_leases.create_index("lease_until")
    await db.cohorts.create_index([("course_id", 1), ("code", 1)], unique=True)
    await db.cohorts.create_index([("course_id", 1), ("status", 1)])
    await db.cohort_members.create_index([("cohort_id", 1), ("learner_id", 1)], unique=True)
    await db.cohort_members.create_index([("learner_id", 1), ("status", 1)])
    await db.live_sessions.create_index([("cohort_id", 1), ("starts_at", 1)])
    await db.attendance.create_index([("session_id", 1), ("learner_id", 1)], unique=True)
    await db.attendance.create_index([("cohort_id", 1), ("status", 1)])
    await db.cohort_members.create_index([("cohort_id", 1), ("status", 1), ("learner_id", 1)])
    await db.live_sessions.create_index([("cohort_id", 1), ("status", 1), ("starts_at", 1)])
    await db.attendance.create_index([("cohort_id", 1), ("learner_id", 1), ("status", 1)])
    await db.live_sessions.create_index([("cohort_id", 1), ("status", 1)])
    await db.live_sessions.create_index([("attendance_locked", 1), ("starts_at", 1)])

async def close_db():
    client.close()

    await db.attendance_compliance_alerts.create_index([("cohort_id", 1), ("learner_id", 1)], unique=True)
    await db.attendance_compliance_alerts.create_index([("state", 1), ("updated_at", -1)])
