import {useEffect,useMemo,useRef,useState} from 'react'
import {useNavigate,useParams} from 'react-router-dom'
import {AlertCircle,ArrowDown,ArrowLeft,ArrowUp,BookOpen,CalendarClock,CheckCircle2,ChevronDown,ChevronRight,Clock3,Copy,Edit3,Eye,FileText,GripVertical,History,Layers,Link2,Plus,RotateCcw,Save,Send,Settings2,Trash2,Video,X} from 'lucide-react'
import {api} from '../../services/api'
import {usePermissions} from '../../contexts/PermissionContext'

const lessonTypes=['reading','video','resource','knowledge_check']
const activityTypes=['practical_task','file_submission','project','checklist','simulation','written_response','evidence_submission','manual_assessment']
const submissionTypes=['text','file','text_and_file','checklist']
const blankLesson={title:'',description:'',lesson_type:'reading',content:'',duration_minutes:'',order:0,is_required:true,video_url:'',release_at:'',prerequisite_lesson_ids:[]}
const blankActivity={title:'',description:'',activity_type:'practical_task',submission_type:'text',instructions:'',materials:'',task_description:'',max_score:100,pass_mark:50,attempts_allowed:1,due_days:'',is_required:true,order:0,prerequisite_activity_ids:[]}
const blankModule={title:'',description:''}
function Modal({title,onClose,children,wide=false}){return <div className="fixed inset-0 z-50 bg-black/45 p-4 flex items-center justify-center"><div className={`six-surface w-full ${wide?'max-w-6xl':'max-w-3xl'} max-h-[94vh] overflow-hidden six-animate-pop`}><div className="px-5 py-4 border-b six-border flex items-center justify-between"><h2 className="font-semibold text-lg">{title}</h2><button title="Close" onClick={onClose} className="p-2 six-hover rounded-lg"><X size={18}/></button></div><div className="p-5 overflow-y-auto max-h-[calc(94vh-70px)]">{children}</div></div></div>}
const Input=p=><input {...p} className={`six-input w-full rounded-xl px-3 py-2.5 outline-none ${p.className||''}`}/>
function Field({label,children,tip}){return <label className="block"><span className="flex items-center gap-1 text-xs font-medium six-muted mb-1.5">{label}{tip&&<span title={tip} className="cursor-help">ⓘ</span>}</span>{children}</label>}
function Section({icon:Icon,title,children,action}){return <section className="six-surface border rounded-2xl overflow-hidden six-animate-rise"><div className="px-4 py-3 border-b six-border flex items-center justify-between"><div className="flex items-center gap-2 font-semibold"><Icon size={17} className="six-primary-text"/>{title}</div>{action}</div>{children}</section>}
function RichEditor({value,onChange}){const ref=useRef(null);useEffect(()=>{if(ref.current && ref.current.innerHTML!==value)ref.current.innerHTML=value||''},[value]);const cmd=(c)=>{ref.current?.focus();document.execCommand(c,false,null);onChange(ref.current?.innerHTML||'')};return <div className="border six-border rounded-xl overflow-hidden"><div className="flex flex-wrap gap-1 p-2 border-b six-border"><button type="button" title="Bold" onClick={()=>cmd('bold')} className="six-icon-button font-bold">B</button><button type="button" title="Italic" onClick={()=>cmd('italic')} className="six-icon-button italic">I</button><button type="button" title="Bulleted list" onClick={()=>cmd('insertUnorderedList')} className="six-icon-button">• List</button><button type="button" title="Numbered list" onClick={()=>cmd('insertOrderedList')} className="six-icon-button">1. List</button><button type="button" title="Heading" onClick={()=>{ref.current?.focus();document.execCommand('formatBlock',false,'h3');onChange(ref.current?.innerHTML||'')}} className="six-icon-button">H</button></div><div ref={ref} contentEditable suppressContentEditableWarning onInput={e=>onChange(e.currentTarget.innerHTML)} className="min-h-44 p-4 outline-none prose max-w-none" data-placeholder="Write the lesson content…"/></div>}

export default function CourseBuilder(){
 const {courseId}=useParams();const nav=useNavigate();const {can}=usePermissions();
 const [course,setCourse]=useState(null),[modules,setModules]=useState([]),[assignments,setAssignments]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState({}),[modal,setModal]=useState(null),[saving,setSaving]=useState(false),[validation,setValidation]=useState(null),[versions,setVersions]=useState([]),[tab,setTab]=useState('structure'),[dirty,setDirty]=useState(false),[lastSaved,setLastSaved]=useState(null)
 const load=async()=>{setLoading(true);try{const [c,ms,as]=await Promise.all([api.course(courseId),api.modules(courseId),api.assignments(courseId)]);setCourse(c);setModules(ms.map(m=>({...m,lessons:null,activities:null,quizzes:null})));setAssignments(as);setError('');setDirty(false)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[courseId])
 useEffect(()=>{if(!dirty)return;const t=setTimeout(()=>setLastSaved(new Date()),1200);return()=>clearTimeout(t)},[dirty])
 const counts=useMemo(()=>({modules:modules.length,lessons:modules.reduce((n,m)=>n+(m.lessons?.length||0),0),activities:modules.reduce((n,m)=>n+(m.activities?.length||0),0),quizzes:modules.reduce((n,m)=>n+(m.quizzes?.length||0),0),assignments:assignments.length,finalProjects:assignments.filter(a=>a.assignment_type==='final_project').length}),[modules,assignments])
 const refreshModule=async id=>{const [lessons,activities,quizzes]=await Promise.all([api.lessons(courseId,id),api.activities(courseId,id),api.quizzes(courseId,id)]);setModules(xs=>xs.map(x=>x.id===id?{...x,lessons,activities,quizzes}:x));return{lessons,activities,quizzes}}
 const toggle=async id=>{const next=!open[id];setOpen(x=>({...x,[id]:next}));if(next){try{await refreshModule(id)}catch(e){setError(e.message)}}}
 const reorderModules=async(from,to)=>{if(to<0||to>=modules.length)return;const next=[...modules];const [item]=next.splice(from,1);next.splice(to,0,item);setModules(next);setDirty(true);try{await Promise.all(next.map((m,i)=>api.updateModule(courseId,m.id,{order:i})))}catch(e){setError(e.message)}}
 const reorderItems=async(m,type,from,to)=>{const list=[...(m[type]||[])];if(to<0||to>=list.length)return;const [item]=list.splice(from,1);list.splice(to,0,item);setModules(xs=>xs.map(x=>x.id===m.id?{...x,[type]:list}:x));setDirty(true);try{await Promise.all(list.map((it,i)=>type==='lessons'?api.updateLesson(courseId,m.id,it.id,{order:i}):type==='activities'?api.updateActivity(it.id,{order:i}):api.updateQuiz(it.id,{order:i})))}catch(e){setError(e.message)}}
 const createModule=async e=>{e.preventDefault();setSaving(true);try{await api.createModule(courseId,{title:e.target.title.value,description:e.target.description.value,order:modules.length});setModal(null);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 const editModule=async(e,m)=>{e.preventDefault();setSaving(true);try{await api.updateModule(courseId,m.id,{title:e.target.title.value,description:e.target.description.value});setModal(null);await load()}catch(x){setError(x.message)}finally{setSaving(false)}}
 const createLesson=async(e,m)=>{e.preventDefault();setSaving(true);try{const prereq=Array.from(e.target.prerequisite_lesson_ids?.selectedOptions||[]).map(o=>o.value);const p={title:e.target.title.value,description:e.target.description.value,lesson_type:e.target.lesson_type.value,content:e.target.content.value,duration_minutes:e.target.duration_minutes.value?Number(e.target.duration_minutes.value):null,order:m.lessons?.length||0,is_required:e.target.is_required.checked,video_url:e.target.video_url.value||null,release_at:e.target.release_at.value?new Date(e.target.release_at.value).toISOString():null,prerequisite_lesson_ids:prereq};await api.createLesson(courseId,m.id,p);setModal(null);await refreshModule(m.id)}catch(x){setError(x.message)}finally{setSaving(false)}}
 const updateLesson=async(e,m,l)=>{e.preventDefault();setSaving(true);try{const prereq=Array.from(e.target.prerequisite_lesson_ids?.selectedOptions||[]).map(o=>o.value);const p={title:e.target.title.value,description:e.target.description.value,lesson_type:e.target.lesson_type.value,content:e.target.content.value,duration_minutes:e.target.duration_minutes.value?Number(e.target.duration_minutes.value):null,is_required:e.target.is_required.checked,video_url:e.target.video_url.value||null,release_at:e.target.release_at.value?new Date(e.target.release_at.value).toISOString():null,prerequisite_lesson_ids:prereq};await api.updateLesson(courseId,m.id,l.id,p);setModal(null);await refreshModule(m.id)}catch(x){setError(x.message)}finally{setSaving(false)}}
 const createActivity=async(e,m)=>{e.preventDefault();setSaving(true);try{const prereq=Array.from(e.target.prerequisite_activity_ids?.selectedOptions||[]).map(o=>o.value);const p={title:e.target.title.value,description:e.target.description.value,activity_type:e.target.activity_type.value,submission_type:e.target.submission_type.value,instructions:e.target.instructions.value,materials:e.target.materials.value.split('\n').map(x=>x.trim()).filter(Boolean),task_description:e.target.task_description.value,max_score:Number(e.target.max_score.value),pass_mark:Number(e.target.pass_mark.value),attempts_allowed:Number(e.target.attempts_allowed.value),due_days:e.target.due_days.value?Number(e.target.due_days.value):null,is_required:e.target.is_required.checked,order:m.activities?.length||0,prerequisite_activity_ids:prereq};await api.createActivity(courseId,m.id,p);setModal(null);await refreshModule(m.id)}catch(x){setError(x.message)}finally{setSaving(false)}}
 const updateActivity=async(e,m,a)=>{e.preventDefault();setSaving(true);try{const prereq=Array.from(e.target.prerequisite_activity_ids?.selectedOptions||[]).map(o=>o.value);await api.updateActivity(a.id,{title:e.target.title.value,description:e.target.description.value,activity_type:e.target.activity_type.value,submission_type:e.target.submission_type.value,instructions:e.target.instructions.value,materials:e.target.materials.value.split('\n').map(x=>x.trim()).filter(Boolean),task_description:e.target.task_description.value,max_score:Number(e.target.max_score.value),pass_mark:Number(e.target.pass_mark.value),attempts_allowed:Number(e.target.attempts_allowed.value),due_days:e.target.due_days.value?Number(e.target.due_days.value):null,is_required:e.target.is_required.checked,prerequisite_activity_ids:prereq});setModal(null);await refreshModule(m.id)}catch(x){setError(x.message)}finally{setSaving(false)}}
 const createAssignment=async e=>{e.preventDefault();setSaving(true);try{const p={title:e.target.title.value,description:e.target.description.value,instructions:e.target.instructions.value,assignment_type:e.target.assignment_type.value,module_id:e.target.module_id.value||null,brief:e.target.brief.value,deliverables:e.target.deliverables.value.split('\n').map(x=>x.trim()).filter(Boolean),submission_type:e.target.submission_type.value,max_score:Number(e.target.max_score.value),pass_mark:Number(e.target.pass_mark.value),attempts_allowed:Number(e.target.attempts_allowed.value),due_days:e.target.due_days.value?Number(e.target.due_days.value):null,is_required:e.target.is_required.checked,order:assignments.length};await api.createAssignment(courseId,p);setModal(null);await load()}catch(x){setError(x.message)}finally{setSaving(false)}}
 const validate=async()=>{try{setValidation(await api.validateCourse(courseId));setTab('review')}catch(e){setError(e.message)}}
 const publish=async()=>{setSaving(true);try{await api.publishCourse(courseId);await load();setValidation(null)}catch(e){setError(e.message);await validate()}finally{setSaving(false)}}
 const loadVersions=async()=>{try{setVersions(await api.courseVersions(courseId));setTab('versions')}catch(e){setError(e.message)}}
 const createRevision=async()=>{setSaving(true);try{await api.createRevision(courseId,'New authoring revision');await load();await loadVersions()}catch(e){setError(e.message)}finally{setSaving(false)}}
 const rollback=async(v)=>{if(!confirm(`Restore version ${v}? A new draft revision will be created.`))return;setSaving(true);try{await api.rollbackVersion(courseId,v,'Restored from version '+v);await load();await loadVersions()}catch(e){setError(e.message)}finally{setSaving(false)}}
 const del=async(fn,id,mid)=>{if(!confirm('Delete this item? This action cannot be undone.'))return;try{await fn(id);if(mid)await refreshModule(mid);else await load()}catch(e){setError(e.message)}}
 if(loading)return <div className="p-8 text-center six-muted">Loading course builder…</div>
 if(!course)return <div className="p-6"><div className="rounded-xl bg-red-50 text-red-700 p-4">{error||'Course not found.'}</div></div>
 return <div className="p-4 sm:p-6 space-y-5">
  <div className="flex items-center gap-3"><button title="Back to courses" onClick={()=>nav('/courses')} className="p-2 six-hover rounded-lg"><ArrowLeft size={19}/></button><div className="min-w-0"><div className="flex items-center gap-2"><BookOpen className="six-primary-text" size={20}/><h1 className="text-2xl font-bold truncate">{course.title}</h1></div><p className="six-muted text-sm mt-1">Advanced Course Authoring · <span className="capitalize">{course.status}</span> · v{course.version_number||1}</p></div><div className="ml-auto flex gap-2 flex-wrap justify-end">{dirty&&<span className="text-xs six-muted self-center">Draft changes{lastSaved?` · autosaved ${lastSaved.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:''}</span>}{can('courses.edit')&&<button title="Open course settings" className="six-button rounded-xl px-3 py-2 flex items-center gap-2" onClick={()=>nav('/courses')}><Settings2 size={16}/>Settings</button>}{can('courses.edit')&&course.status==='published'&&<button title="Create an editable draft revision" className="rounded-xl px-3 py-2 border six-border flex items-center gap-2" onClick={createRevision}><Copy size={16}/>New revision</button>}{can('courses.publish')&&<button title="Run the publishing checklist" className="six-button rounded-xl px-3 py-2 flex items-center gap-2" disabled={saving} onClick={publish}><Send size={16}/>Publish</button>}</div></div>
  {error&&<div className="rounded-xl bg-red-50 text-red-700 p-3 flex gap-2"><AlertCircle size={18}/><span>{error}</span></div>}
  <div className="grid grid-cols-2 md:grid-cols-6 gap-3 six-stagger">{Object.entries({Modules:counts.modules,Lessons:counts.lessons,Activities:counts.activities,Quizzes:counts.quizzes,Assignments:counts.assignments,'Final projects':counts.finalProjects}).map(([k,v])=><div key={k} className="six-surface border rounded-xl p-3"><div className="text-xs six-muted">{k}</div><div className="text-xl font-bold mt-1">{v}</div></div>)}</div>
  <div className="six-surface border rounded-2xl p-1 flex flex-wrap gap-1"><button onClick={()=>setTab('structure')} className={`px-4 py-2 rounded-xl text-sm ${tab==='structure'?'six-button':''}`}>Structure</button><button onClick={()=>setTab('assignments')} className={`px-4 py-2 rounded-xl text-sm ${tab==='assignments'?'six-button':''}`}>Assignments & Projects</button><button onClick={validate} className={`px-4 py-2 rounded-xl text-sm ${tab==='review'?'six-button':''}`}>Publishing checklist</button><button onClick={loadVersions} className={`px-4 py-2 rounded-xl text-sm flex items-center gap-1 ${tab==='versions'?'six-button':''}`}><History size={15}/>Version history</button></div>
  {tab==='structure'&&<div className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Course structure</h2><p className="text-sm six-muted">Drag modules and content to reorder. Use the tips to keep the learner journey clear.</p></div>{can('modules.create')&&<button title="Add a new module" className="six-button rounded-xl px-3 py-2 flex items-center gap-2" onClick={()=>setModal({type:'module'})}><Plus size={16}/>Module</button>}</div>
   {modules.map((m,mi)=><Section key={m.id} icon={Layers} title={<div className="flex items-center gap-2"><span>{mi+1}. {m.title}</span><span className="text-xs font-normal six-muted">{m.lessons?.length??'…'} lessons</span></div>} action={<div className="flex gap-1"><button title="Move module up" disabled={mi===0} onClick={()=>reorderModules(mi,mi-1)} className="six-icon-button"><ArrowUp size={15}/></button><button title="Move module down" disabled={mi===modules.length-1} onClick={()=>reorderModules(mi,mi+1)} className="six-icon-button"><ArrowDown size={15}/></button><button title="Edit module" onClick={()=>setModal({type:'editModule',module:m})} className="six-icon-button"><Edit3 size={15}/></button><button title="Expand module" onClick={()=>toggle(m.id)} className="six-icon-button">{open[m.id]?<ChevronDown size={17}/>:<ChevronRight size={17}/>}</button></div>}>
      {open[m.id]&&<div className="p-4 space-y-3"><div className="six-task-tip text-sm"><strong>Authoring tip:</strong> Keep each lesson focused on one outcome. Put files in the Content Library and use prerequisites only when the learning sequence truly matters.</div>
       {m.lessons?.map((l,i)=><div key={l.id} className="border six-border rounded-xl p-3 flex gap-3 items-start six-task-card"><GripVertical size={17} className="six-muted mt-1"/><div className="flex-1"><div className="flex items-center gap-2"><FileText size={16} className="six-primary-text"/><strong>{i+1}. {l.title}</strong>{l.is_required&&<span className="text-[10px] rounded-full px-2 py-0.5 six-primary-soft six-primary-text">Required</span>}</div><p className="text-xs six-muted mt-1">{l.lesson_type} · {l.duration_minutes||0} min {l.video_url?'· video':''} {l.release_at?'· scheduled':''}</p></div><div className="flex gap-1"><button title="Move lesson up" disabled={i===0} onClick={()=>reorderItems(m,'lessons',i,i-1)} className="six-icon-button"><ArrowUp size={14}/></button><button title="Move lesson down" disabled={i===m.lessons.length-1} onClick={()=>reorderItems(m,'lessons',i,i+1)} className="six-icon-button"><ArrowDown size={14}/></button><button title="Edit lesson" onClick={()=>setModal({type:'editLesson',module:m,lesson:l})} className="six-icon-button"><Edit3 size={14}/></button><button title="Delete lesson" onClick={()=>del(id=>api.deleteLesson(courseId,m.id,id),l.id,m.id)} className="six-icon-button"><Trash2 size={14}/></button></div></div>)}
       {m.activities?.map((a,i)=><div key={a.id} className="border six-border rounded-xl p-3 flex gap-3 items-start six-task-card"><GripVertical size={17} className="six-muted mt-1"/><div className="flex-1"><strong>{a.title}</strong><p className="text-xs six-muted mt-1">Activity · {a.activity_type} · pass mark {a.pass_mark}% · {a.status}</p></div><div className="flex gap-1"><button title="Move activity up" disabled={i===0} onClick={()=>reorderItems(m,'activities',i,i-1)} className="six-icon-button"><ArrowUp size={14}/></button><button title="Move activity down" disabled={i===m.activities.length-1} onClick={()=>reorderItems(m,'activities',i,i+1)} className="six-icon-button"><ArrowDown size={14}/></button><button title="Edit activity" onClick={()=>setModal({type:'editActivity',module:m,activity:a})} className="six-icon-button"><Edit3 size={14}/></button><button title="Delete activity" onClick={()=>del(id=>api.deleteActivity(id),a.id,m.id)} className="six-icon-button"><Trash2 size={14}/></button></div></div>)}
       {m.quizzes?.map((q,i)=><div key={q.id} className="border six-border rounded-xl p-3 flex gap-3 items-start six-task-card"><GripVertical size={17} className="six-muted mt-1"/><div className="flex-1"><strong>{q.title}</strong><p className="text-xs six-muted mt-1">Assessment · pass mark {q.pass_mark}% · {q.status}</p></div><div className="flex gap-1"><button title="Move assessment up" disabled={i===0} onClick={()=>reorderItems(m,'quizzes',i,i-1)} className="six-icon-button"><ArrowUp size={14}/></button><button title="Move assessment down" disabled={i===m.quizzes.length-1} onClick={()=>reorderItems(m,'quizzes',i,i+1)} className="six-icon-button"><ArrowDown size={14}/></button></div></div>)}
       <div className="flex flex-wrap gap-2 pt-2">{can('lessons.create')&&<button title="Create a lesson" onClick={()=>setModal({type:'lesson',module:m})} className="border six-border rounded-xl px-3 py-2 text-sm flex items-center gap-2"><Plus size={15}/>Lesson</button>}{can('activities.create')&&<button title="Create a hands-on activity" onClick={()=>setModal({type:'activity',module:m})} className="border six-border rounded-xl px-3 py-2 text-sm flex items-center gap-2"><Plus size={15}/>Activity</button>}{can('quizzes.create')&&<button title="Create an assessment" onClick={()=>setModal({type:'quiz',module:m})} className="border six-border rounded-xl px-3 py-2 text-sm flex items-center gap-2"><Plus size={15}/>Assessment</button>}</div>
      </div>}
   </Section>)}
   {!modules.length&&<div className="six-surface border rounded-2xl p-10 text-center six-muted">Start by adding a module. Then build lessons, practical activities, and assessments inside it.</div>}
  </div>}
  {tab==='assignments'&&<Section icon={FileText} title="Assignments & final projects" action={can('assignments.create')&&<button title="Add assignment or final project" onClick={()=>setModal({type:'assignment'})} className="six-button rounded-xl px-3 py-2 text-sm flex items-center gap-2"><Plus size={15}/>Add</button>}><div className="p-4 space-y-3">{assignments.map(a=><div key={a.id} className="border six-border rounded-xl p-4 flex items-center gap-3 six-task-card"><div className="flex-1"><strong>{a.title}</strong><p className="text-xs six-muted mt-1">{a.assignment_type} · pass mark {a.pass_mark}% · {a.status}</p></div><button title="Edit assignment" onClick={()=>setModal({type:'assignmentEdit',assignment:a})} className="six-icon-button"><Edit3 size={15}/></button></div>)}{!assignments.length&&<div className="text-center six-muted py-8">No assignments yet.</div>}</div></Section>}
  {tab==='review'&&<Section icon={CheckCircle2} title="Publishing checklist"><div className="p-4">{validation?<div className="space-y-4"><div className={`rounded-xl p-4 ${validation.valid?'six-complete':'bg-red-50 text-red-700'}`}><strong>{validation.valid?'Ready to publish':'Needs attention'}</strong><p className="text-sm mt-1">{validation.valid?'All blocking checks passed.':'Fix the blocking issues below before publishing.'}</p></div>{validation.errors?.map((x,i)=><div key={i} className="flex gap-2 p-3 rounded-xl bg-red-50 text-red-700 text-sm"><AlertCircle size={16}/>{x.message}</div>)}{validation.warnings?.map((x,i)=><div key={i} className="flex gap-2 p-3 rounded-xl bg-amber-50 text-amber-800 text-sm"><AlertCircle size={16}/>{x.message}</div>)}<button title="Run checklist again" onClick={validate} className="border six-border rounded-xl px-3 py-2 text-sm">Refresh checklist</button></div>:<button onClick={validate} className="six-button rounded-xl px-4 py-2">Run publishing checklist</button>}</div></Section>}
  {tab==='versions'&&<Section icon={History} title="Version history"><div className="p-4 space-y-3">{versions.map(v=><div key={v.id} className="border six-border rounded-xl p-4 flex items-center gap-3"><div className="w-10 h-10 rounded-xl six-primary-soft six-primary-text grid place-items-center font-bold">v{v.version_number}</div><div className="flex-1"><strong className="capitalize">{v.status}</strong><p className="text-xs six-muted mt-1">{v.change_note||'No change note'} · {new Date(v.created_at).toLocaleString()}</p></div>{v.status!=='published'&&can('courses.edit')&&<button title="Restore this version into a new draft" onClick={()=>rollback(v.version_number)} className="border six-border rounded-xl px-3 py-2 text-sm flex gap-2 items-center"><RotateCcw size={15}/>Restore</button>}</div>)}{!versions.length&&<div className="text-center six-muted py-8">No version snapshots found yet.</div>}</div></Section>}

 {modal?.type==='module'&&<Modal title="Add module" onClose={()=>setModal(null)}><form onSubmit={createModule} className="space-y-4"><Field label="Module title"><Input name="title" required autoFocus placeholder="e.g. Module 1 — Foundations"/></Field><Field label="Description"><textarea name="description" className="six-input w-full rounded-xl p-3 min-h-24"/></Field><button disabled={saving} className="six-button rounded-xl px-4 py-2">Save module</button></form></Modal>}
 {modal?.type==='editModule'&&<Modal title="Edit module" onClose={()=>setModal(null)}><form onSubmit={e=>editModule(e,modal.module)} className="space-y-4"><Field label="Module title"><Input name="title" required defaultValue={modal.module.title}/></Field><Field label="Description"><textarea name="description" defaultValue={modal.module.description} className="six-input w-full rounded-xl p-3 min-h-24"/></Field><button disabled={saving} className="six-button rounded-xl px-4 py-2">Save changes</button></form></Modal>}
 {modal?.type==='lesson'&&<LessonForm module={modal.module} saving={saving} onClose={()=>setModal(null)} onSubmit={createLesson} />}
 {modal?.type==='editLesson'&&<LessonForm module={modal.module} lesson={modal.lesson} saving={saving} onClose={()=>setModal(null)} onSubmit={e=>updateLesson(e,modal.module,modal.lesson)} />}
 {modal?.type==='activity'&&<ActivityForm module={modal.module} saving={saving} onClose={()=>setModal(null)} onSubmit={createActivity}/>} {modal?.type==='editActivity'&&<ActivityForm module={modal.module} activity={modal.activity} saving={saving} onClose={()=>setModal(null)} onSubmit={e=>updateActivity(e,modal.module,modal.activity)}/>} 
 {modal?.type==='assignment'&&<AssignmentForm modules={modules} saving={saving} onClose={()=>setModal(null)} onSubmit={createAssignment}/>} 
 {modal?.type==='assignmentEdit'&&<AssignmentEdit assignment={modal.assignment} saving={saving} onClose={()=>setModal(null)} onSaved={async()=>{setModal(null);await load()}}/>}
 </div>
}
function LessonForm({module,lesson,saving,onClose,onSubmit}){const v=lesson||blankLesson;const [content,setContent]=useState(v.content||'');const submit=e=>{e.preventDefault();e.target.content.value=content;onSubmit(e)};return <Modal wide title={lesson?'Edit lesson':'Create lesson'} onClose={onClose}><form onSubmit={submit} className="space-y-4"><div className="grid md:grid-cols-2 gap-4"><Field label="Title"><Input name="title" required defaultValue={v.title}/></Field><Field label="Lesson type"><select name="lesson_type" defaultValue={v.lesson_type} className="six-input w-full rounded-xl px-3 py-2.5">{lessonTypes.map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="Description"><Input name="description" defaultValue={v.description}/></Field><Field label="Lesson content" tip="Use the toolbar for basic formatting. Content is stored as HTML and displayed in the learner player."><input type="hidden" name="content" value={content} readOnly/><RichEditor value={content} onChange={setContent}/></Field><div className="grid md:grid-cols-3 gap-4"><Field label="Duration (minutes)"><Input name="duration_minutes" type="number" min="0" defaultValue={v.duration_minutes||''}/></Field><Field label="Video URL" tip="For hosted or embedded course video."><Input name="video_url" defaultValue={v.video_url||''} placeholder="https://…"/></Field><Field label="Release date/time"><Input name="release_at" type="datetime-local" defaultValue={v.release_at?new Date(v.release_at).toISOString().slice(0,16):''}/></Field></div><Field label="Prerequisite lessons" tip="Learners should complete these first."><select multiple name="prerequisite_lesson_ids" defaultValue={v.prerequisite_lesson_ids||[]} className="six-input w-full rounded-xl p-2 min-h-28">{(module.lessons||[]).filter(x=>x.id!==lesson?.id).map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></Field><label className="flex gap-2 items-center text-sm"><input name="is_required" type="checkbox" defaultChecked={v.is_required}/> Required for course completion</label><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="border six-border rounded-xl px-4 py-2">Cancel</button><button disabled={saving} className="six-button rounded-xl px-4 py-2 flex items-center gap-2"><Save size={15}/>{lesson?'Save changes':'Create lesson'}</button></div></form></Modal>}
function ActivityForm({module,activity,saving,onClose,onSubmit}){const v=activity||blankActivity;return <Modal title={activity?'Edit activity':'Create hands-on activity'} onClose={onClose}><form onSubmit={onSubmit} className="space-y-4"><Field label="Title"><Input name="title" required defaultValue={v.title}/></Field><Field label="Description"><Input name="description" defaultValue={v.description}/></Field><div className="grid md:grid-cols-2 gap-4"><Field label="Activity type"><select name="activity_type" defaultValue={v.activity_type} className="six-input w-full rounded-xl px-3 py-2.5">{activityTypes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Submission type"><select name="submission_type" defaultValue={v.submission_type} className="six-input w-full rounded-xl px-3 py-2.5">{submissionTypes.map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="Instructions"><textarea name="instructions" defaultValue={v.instructions} className="six-input w-full rounded-xl p-3 min-h-28"/></Field><Field label="Task description"><textarea name="task_description" defaultValue={v.task_description} className="six-input w-full rounded-xl p-3 min-h-24"/></Field><Field label="Materials" tip="One item per line."><textarea name="materials" defaultValue={Array.isArray(v.materials)?v.materials.join('\n'):v.materials} className="six-input w-full rounded-xl p-3 min-h-24"/></Field><div className="grid md:grid-cols-4 gap-4"><Field label="Max score"><Input name="max_score" type="number" min="1" defaultValue={v.max_score}/></Field><Field label="Pass mark %"><Input name="pass_mark" type="number" min="0" max="100" defaultValue={v.pass_mark}/></Field><Field label="Attempts"><Input name="attempts_allowed" type="number" min="1" defaultValue={v.attempts_allowed}/></Field><Field label="Due days"><Input name="due_days" type="number" min="0" defaultValue={v.due_days||''}/></Field></div><Field label="Prerequisite activities"><select multiple name="prerequisite_activity_ids" defaultValue={v.prerequisite_activity_ids||[]} className="six-input w-full rounded-xl p-2 min-h-24">{(module.activities||[]).filter(x=>x.id!==activity?.id).map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></Field><label className="flex gap-2 items-center text-sm"><input name="is_required" type="checkbox" defaultChecked={v.is_required}/> Required for completion</label><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="border six-border rounded-xl px-4 py-2">Cancel</button><button disabled={saving} className="six-button rounded-xl px-4 py-2">{activity?'Save changes':'Create activity'}</button></div></form></Modal>}
function AssignmentForm({modules,saving,onClose,onSubmit}){return <Modal title="Create assignment or final project" onClose={onClose}><form onSubmit={onSubmit} className="space-y-4"><Field label="Title"><Input name="title" required/></Field><div className="grid md:grid-cols-2 gap-4"><Field label="Type"><select name="assignment_type" className="six-input w-full rounded-xl px-3 py-2.5"><option value="assignment">Assignment</option><option value="final_project">Final project</option></select></Field><Field label="Module (optional)"><select name="module_id" className="six-input w-full rounded-xl px-3 py-2.5"><option value="">Course-level</option>{modules.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></Field></div><Field label="Description"><Input name="description"/></Field><Field label="Instructions"><textarea name="instructions" className="six-input w-full rounded-xl p-3 min-h-24"/></Field><Field label="Project brief"><textarea name="brief" className="six-input w-full rounded-xl p-3 min-h-24"/></Field><Field label="Deliverables" tip="One deliverable per line."><textarea name="deliverables" className="six-input w-full rounded-xl p-3 min-h-24"/></Field><div className="grid md:grid-cols-4 gap-4"><Field label="Submission"><select name="submission_type" className="six-input w-full rounded-xl px-3 py-2.5"><option value="text_and_file">Text + file</option><option value="text">Text</option><option value="file">File</option></select></Field><Field label="Max score"><Input name="max_score" type="number" defaultValue="100"/></Field><Field label="Pass mark %"><Input name="pass_mark" type="number" defaultValue="50"/></Field><Field label="Attempts"><Input name="attempts_allowed" type="number" defaultValue="1" min="1"/></Field></div><label className="flex gap-2 items-center text-sm"><input name="is_required" type="checkbox" defaultChecked/> Required</label><div className="flex justify-end"><button disabled={saving} className="six-button rounded-xl px-4 py-2">Create</button></div></form></Modal>}
function AssignmentEdit({assignment,saving,onClose,onSaved}){const [busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);try{await api.updateAssignment(assignment.id,{title:e.target.title.value,description:e.target.description.value,instructions:e.target.instructions.value,brief:e.target.brief.value,max_score:Number(e.target.max_score.value),pass_mark:Number(e.target.pass_mark.value),attempts_allowed:Number(e.target.attempts_allowed.value)});await onSaved()}catch(e){alert(e.message)}finally{setBusy(false)}};return <Modal title="Edit assignment" onClose={onClose}><form onSubmit={submit} className="space-y-4"><Field label="Title"><Input name="title" required defaultValue={assignment.title}/></Field><Field label="Description"><Input name="description" defaultValue={assignment.description}/></Field><Field label="Instructions"><textarea name="instructions" defaultValue={assignment.instructions} className="six-input w-full rounded-xl p-3 min-h-24"/></Field><Field label="Brief"><textarea name="brief" defaultValue={assignment.brief} className="six-input w-full rounded-xl p-3 min-h-24"/></Field><div className="grid grid-cols-3 gap-4"><Field label="Max score"><Input name="max_score" type="number" defaultValue={assignment.max_score}/></Field><Field label="Pass mark"><Input name="pass_mark" type="number" defaultValue={assignment.pass_mark}/></Field><Field label="Attempts"><Input name="attempts_allowed" type="number" defaultValue={assignment.attempts_allowed}/></Field></div><button disabled={busy||saving} className="six-button rounded-xl px-4 py-2">Save changes</button></form></Modal>}
