import { useEffect, useMemo, useState } from 'react'
import { Archive, Download, File, FileArchive, FileAudio, FileImage, FileSpreadsheet, FileText, FileVideo, FolderOpen, Pencil, Plus, Search, Trash2, Upload, X } from 'lucide-react'
import { api } from '../../services/api'
import { usePermissions } from '../../contexts/PermissionContext'

const types=['','document','image','video','audio','spreadsheet','presentation','archive','other']
const iconFor=t=>({document:FileText,image:FileImage,video:FileVideo,audio:FileAudio,spreadsheet:FileSpreadsheet,presentation:FileText,archive:FileArchive}[t]||File)
const formatSize=n=>{if(!n)return '0 B';const u=['B','KB','MB','GB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return `${x.toFixed(i?1:0)} ${u[i]}`}
export default function ContentLibrary(){
 const {can}=usePermissions(); const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [search,setSearch]=useState(''); const [type,setType]=useState(''); const [status,setStatus]=useState('active'); const [showUpload,setShowUpload]=useState(false); const [editing,setEditing]=useState(null); const [busy,setBusy]=useState(false)
 const load=async()=>{setLoading(true);setError('');try{setItems(await api.content({content_type:type,status}))}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[type,status])
 const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.original_filename} ${x.description} ${x.folder}`.toLowerCase().includes(search.toLowerCase())),[items,search])
 const remove=async x=>{if(!confirm(`Delete “${x.name}”?`))return;setBusy(true);try{await api.deleteContent(x.id);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const archive=async x=>{setBusy(true);try{await api.archiveContent(x.id);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const download=async x=>{try{const blob=await api.downloadContent(x.id);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=x.original_filename;a.click();URL.revokeObjectURL(url)}catch(e){setError(e.message)}}
 return <div className="space-y-6">
  <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><div className="text-sm six-primary-text font-semibold">Administration</div><h1 className="text-3xl font-bold mt-1">Content Library</h1><p className="six-muted mt-1">Centralize learning resources and manage reusable files for courses, lessons, and activities.</p></div>{can('content.upload')&&<button onClick={()=>setShowUpload(true)} className="six-primary-bg text-white px-4 py-2.5 rounded-xl inline-flex items-center gap-2"><Plus size={18}/>Upload content</button>}</div>
  <div className="six-surface border p-4 flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-3 six-muted"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search files, folders, descriptions..." className="w-full pl-9 pr-3 py-2.5 border rounded-xl bg-transparent"/></div><select value={type} onChange={e=>setType(e.target.value)} className="border rounded-xl px-3 py-2.5 bg-transparent"><option value="">All types</option>{types.slice(1).map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="border rounded-xl px-3 py-2.5 bg-transparent"><option value="active">Active</option><option value="archived">Archived</option></select></div>
  {error&&<div className="border border-red-300 bg-red-50 text-red-700 rounded-xl p-3 text-sm">{error}</div>}
  {loading?<div className="six-surface border p-10 text-center six-muted">Loading content library...</div>:filtered.length===0?<div className="six-surface border p-10 text-center"><FolderOpen className="mx-auto six-muted"/><p className="font-semibold mt-3">No content found</p><p className="six-muted text-sm mt-1">Upload a reusable learning resource to get started.</p></div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(x=>{const Icon=iconFor(x.content_type);return <div key={x.id} className="six-surface border p-5"><div className="flex items-start justify-between gap-3"><div className="w-11 h-11 rounded-xl flex items-center justify-center bg-[var(--primary-soft)] six-primary-text"><Icon size={21}/></div><span className={`text-xs px-2 py-1 rounded-full ${x.status==='active'?'bg-green-100 text-green-700':'bg-gray-100 text-gray-600'}`}>{x.status}</span></div><h3 className="font-semibold mt-4 truncate" title={x.name}>{x.name}</h3><p className="text-xs six-muted truncate mt-1">{x.original_filename}</p><p className="text-sm six-muted mt-3 line-clamp-2 min-h-10">{x.description||'No description provided.'}</p><div className="flex items-center justify-between text-xs six-muted mt-4"><span>{formatSize(x.size_bytes)}</span><span>{x.extension || x.content_type}</span></div>{x.folder&&<div className="text-xs six-muted mt-2">Folder: {x.folder}</div>}<div className="flex gap-2 mt-4 pt-4 border-t"><button onClick={()=>download(x)} className="flex-1 border rounded-lg py-2 text-sm inline-flex justify-center items-center gap-1"><Download size={15}/>Download</button>{can('content.edit')&&<button onClick={()=>setEditing(x)} className="border rounded-lg px-3" title="Edit"><Pencil size={15}/></button>}{can('content.delete')&&x.status==='active'&&<button onClick={()=>archive(x)} disabled={busy} className="border rounded-lg px-3" title="Archive"><Archive size={15}/></button>}{can('content.delete')&&<button onClick={()=>remove(x)} disabled={busy} className="border rounded-lg px-3 text-red-600" title="Delete"><Trash2 size={15}/></button>}</div></div>})}</div>}
  {showUpload&&<UploadModal onClose={()=>setShowUpload(false)} onSaved={load}/>} {editing&&<EditModal item={editing} onClose={()=>setEditing(null)} onSaved={load}/>} 
 </div>
}
function UploadModal({onClose,onSaved}){const [file,setFile]=useState(null),[name,setName]=useState(''),[description,setDescription]=useState(''),[folder,setFolder]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const save=async e=>{e.preventDefault();if(!file)return setError('Select a file.');setBusy(true);try{await api.uploadContent({file,name,description,folder});onClose();await onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}};return <Modal title="Upload content" onClose={onClose}><form onSubmit={save} className="space-y-4"><input type="file" required onChange={e=>setFile(e.target.files?.[0])} className="w-full border rounded-xl p-2.5"/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Display name (optional)" className="w-full border rounded-xl p-2.5"/><input value={folder} onChange={e=>setFolder(e.target.value)} placeholder="Folder (optional)" className="w-full border rounded-xl p-2.5"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description" rows={3} className="w-full border rounded-xl p-2.5"/>{error&&<p className="text-sm text-red-600">{error}</p>}<Actions busy={busy} onClose={onClose} label="Upload"/></form></Modal>}
function EditModal({item,onClose,onSaved}){const [name,setName]=useState(item.name),[description,setDescription]=useState(item.description||''),[folder,setFolder]=useState(item.folder||''),[busy,setBusy]=useState(false),[error,setError]=useState('');const save=async e=>{e.preventDefault();setBusy(true);try{await api.updateContent(item.id,{name,description,folder});onClose();await onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}};return <Modal title="Edit content" onClose={onClose}><form onSubmit={save} className="space-y-4"><input value={name} onChange={e=>setName(e.target.value)} required className="w-full border rounded-xl p-2.5"/><input value={folder} onChange={e=>setFolder(e.target.value)} placeholder="Folder" className="w-full border rounded-xl p-2.5"/><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} className="w-full border rounded-xl p-2.5"/>{error&&<p className="text-sm text-red-600">{error}</p>}<Actions busy={busy} onClose={onClose} label="Save changes"/></form></Modal>}
const Actions=({busy,onClose,label})=><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="border rounded-xl px-4 py-2">Cancel</button><button disabled={busy} className="six-primary-bg text-white rounded-xl px-4 py-2 inline-flex gap-2 items-center"><Upload size={16}/>{busy?'Saving...':label}</button></div>
const Modal=({title,onClose,children})=><div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="w-full max-w-lg six-surface border rounded-2xl shadow-xl"><div className="flex items-center justify-between p-5 border-b"><h2 className="font-bold text-lg">{title}</h2><button onClick={onClose}><X size={20}/></button></div><div className="p-5">{children}</div></div></div>
